### ISSUE TITLE
Joining effort, integrate into Spring Boot Starter?

### ISSUE THREAD

**Issue by saturnism** [LogNet/grpc-spring-boot-starter#1]
Hiya!

I just discovered this independently from something I was working on. Would you be interested in getting similar functionalities into the main spring boot starters?

A few minor differences:
- No Java 8 dependence
- Configurable discovery mechanism
- Focused on the server side, we can have a separate grpc-client starter
- Preconfigured Maven plugin

The last one is big for Maven users, where the getting started experience, with stub generation, will become super easy when using the preconfigured plugin from the parent POM.

https://github.com/spring-projects/spring-boot/pull/5206

Thanks!

**Comment by jvmlet** [comment]
Hi Ray
Great to see the community engagement. 
I'm defenently interested in your involvement. 
I'll eliminate the Java 8 dependency and think about how discovery process could be customized. 
 I'm  gradle addicted,  so maven plugin is on you  :-)
Please PR the Readme file on road map section with the features you have in mind.
Regards 
Alexander

**Comment by sdeleuze** [comment]
Hey @saturnism and @jvmlet, any news about the joint effort?

**Comment by jvmlet** [comment]
Hello @sdeleuze 
As you can see,I've never got response from Ray, on the other hand I'll be glad to collaborate with everyone who is interested, including Pivotal team :-)

**Comment by saturnism** [comment]
hiya! sorry abt the delay here - i've been quite busy. Could I first trouble you to add the LICENSE file into the repo? I know it's in the README but it's better to have it in the repo.

I have the pom.xml in my PR spring-projects/spring-boot#5206

Aside from that, I think most of the things are comparable. IIRC, GRPC team also made headways to add a common marker interface for GRPC stubs.  It's one of the bigger issues I had w/ the GRPC generated code.

**Comment by otrosien** [comment]
Let's have a look what can be included from that PR. https://github.com/spring-projects/spring-boot/pull/5206/files

**Comment by otrosien** [comment]
@jvmlet *ping*

**Comment by cbornet** [comment]
@saturnism would you do the client starter ?

**Comment by magg** [comment]
any update on this?

**Comment by jvmlet** [comment]
What kind of update do you expect?

**Comment by magg** [comment]
this repo and @saturnism's repo to merge at least... and for the starter to be integrated into spring boot starters

**Comment by jvmlet** [comment]
1. What features from suturnism's repo are you missing? 
2. It's up to Spring team to decide whether to integrate this into official starters....

**Comment by magg** [comment]
1. the grpc client starter would be nice to have for instance....
2. Oh I see

**Comment by jvmlet** [comment]
1. I don't think he has client starter.  May be if I have time I'll post about integrating grpc client with eureka

**Comment by jorgheymans** [comment]
TBH i don't think service discovery should be part of this starter. let it
stay focused as it is now.

**Comment by cbornet** [comment]
A grpc client starter would be useful though. It could be a separate project.

**Comment by magg** [comment]
isn't this the client?

https://github.com/saturnism/spring-boot-starter-grpc/tree/master/grpc-client-starter

**Comment by magg** [comment]
@jvmlet a guide on grpc client with eureka would be nice, but yeah not part of the starter

**Comment by LuckyDukang** [comment]
@magg  I found a repo. It  support grpc client with eureka.
https://github.com/yidongnan/grpc-spring-boot-starter

**Comment by magg** [comment]
@LuckyDukang thanks, I will check it out.

I would want this repo, to include those things. In the mean time that will do

regards

**Comment by jvmlet** [comment]
@magg, I'll add the section to Readme how to configure and integrate with eureka, its few lines in configuration file and I don't see the added value (meanwhile )  to have the  specific project for this feature given the simplicity of having this done thanks to great spring cloud framework.

**Comment by magg** [comment]
@jvmlet  yeah the Eureka thing can only be an example like in @saturnism  or @yidongnan... I was requesting having in this project the grpc client (I think it is a great addition) since this project seems to be more active....

**Comment by jvmlet** [comment]
@LuckyDukang ,  @magg I don't think  eureka integration client starter has additional value, taking into consideration the simplicity of solution provided by `spring-cloud-netflix` project. Moreover, I would say it will hide from you the low level API and you will not have the full power of Eureka configuration.
I've added to [README ](https://github.com/LogNet/grpc-spring-boot-starter#eureka-integration) the example of how this starter could be integrated with Eureka.
