### ISSUE TITLE
Use grpc instead of feign

### ISSUE THREAD

**Issue by whd-mtt** [LogNet/grpc-spring-boot-starter#101]
In my springcloud project, the feign was used for communicating among those micro-services, this communication mode based on http 1.0 have something performance Bottle-neck, so I decide to replace feign with grpc , Can the project resolve my problem?

**Comment by jvmlet** [comment]
Yes, grpc works on top of http/2

**Comment by whd-mtt** [comment]
> Yes, grpc works on top of http/2

You didn't answer my question directly, Can you tell me exactly how to do it?

**Comment by whd-mtt** [comment]
@jvmlet You didn't answer my question directly, Can you tell me exactly how to do it?

**Comment by jvmlet** [comment]
I would suggest you to familiar yourself with grpc getting started guide  https://grpc.io/docs/quickstart/java.html
