### ISSUE TITLE
No logs were shown when starting spring boot using Kotlin

### ISSUE THREAD

**Issue by bppdanto-t** [LogNet/grpc-spring-boot-starter#104]
I saw that this project is using Lombok for logging and it seems it's not compatible with Kotlin (https://stackoverflow.com/questions/35517325/kotlin-doesnt-see-java-lombok-accessors), thus there are no logs when trying to start the app.

Could you change the logging with others that compatible with Kotlin?

**Comment by jvmlet** [comment]
@bppdanto-t , is this working for you ?

**Comment by bppdanto-t** [comment]
Actually, it doesn't work when compiling this repo under Kotlin, but it works fine if used as a dependency. Thanks for the response
