### ISSUE TITLE
Release with gRPC 1.16.1

### ISSUE THREAD

**Issue by suztomo** [LogNet/grpc-spring-boot-starter#106]
Copy from https://github.com/spring-cloud/spring-cloud-sleuth/issues/1186

[`org.springframework.cloud:spring-cloud-sleuth-core:2.1.0.RC3`][1] depends on following two Maven artifacts.

- [`io.github.lognet:grpc-spring-boot-starter:3.0.0`][2]
  This depends on `io.grpc:grpc-netty:jar:1.15.1`
- [`io.zipkin.brave:brave-instrumentation-grpc:5.6.0`][3]
  This depends on `io.grpc:grpc-all:1.16.1`

They, however, do not have same version of transitive gRPC dependency (1.**15**.1 vs. 1.**16**.1). Such inconsistencies carries a risk of raising a run-time exception (Example: https://github.com/spring-cloud/spring-cloud-gcp/issues/1373).

# Solution

In order to mitigate the risk, it would be great if spring-cloud-sleuth has consistent gRPC version in its transitive dependencies, but, as of this issue creation, the latest grpc-spring-boot-starter ([3.0.1-SNAPSHOT][4]) has only 1.15.1.

Would you have a release of grpc-spring-boot-starter with gRPC 1.16.1 dependency?

[1]: http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-sleuth-core/2.1.0.RC3/spring-cloud-sleuth-core-2.1.0.RC3.pom
[2]: https://search.maven.org/artifact/io.github.lognet/grpc-spring-boot-starter/3.0.0/jar
[3]: https://search.maven.org/artifact/io.zipkin.brave/brave-instrumentation-grpc/5.6.0/jar
[4]: https://search.maven.org/artifact/io.github.lognet/grpc-spring-boot-starter/3.0.1-SNAPHSOT/jar

**Comment by jvmlet** [comment]
Hi @suztomo 
You have the full control over  gRPC version being used.
To upgrade, simply add the version you want to your gradle build file  :

`````
    compile "io.grpc:grpc-netty:${grpcVersion}"
    compile "io.grpc:grpc-services:${grpcVersion}"
````
To downgrade :
````
configurations.all {
    resolutionStrategy {
        force  "io.grpc:grpc-netty:${grpcVersion}"
         force "io.grpc:grpc-services:${grpcVersion}"
    }
}
````
Hope this helps

**Comment by suztomo** [comment]
Thank you for response. I'll check how different gRPC versgons work with this.

**Comment by jvmlet** [comment]
@suztomo ,[FYI ](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/ReleaseNotes.adoc)
Please allow few hours for nexus to sync up
