### ISSUE TITLE
Use of `io.grpc:netty` dependency conflicts with Netty version provided by Spring Boot

### ISSUE THREAD

**Issue by crewmanmud** [LogNet/grpc-spring-boot-starter#108]
Running into classpath conflicts with Spring Boot 2.1.0 and an older version of `grpc-spring-boot-starter`.  Specifically, the Spring Boot version of Netty wins out over the `io.grpc:netty` version, causing compatibility issues (i.e. with `@ExperimentalApi` methods that have disappeared).

Given that the Netty instances aren't shared between Spring Boot Reactive and gRPC, could we use the `io.grpc:netty-shaded` dependency on the starter rather than `io.grpc:netty`?
https://github.com/LogNet/grpc-spring-boot-starter/blob/31d1513b420b1d0d0610738a8d97dc6f970e4d91/grpc-spring-boot-starter/build.gradle

Over at https://github.com/grpc/grpc-java, they seem to recommend the `io.grpc:netty-shaded` dependency rather than the vanilla version (given their "Download" instructions).  Further information RE classpath and Netty/grpc-java compatibility:
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty

**Comment by jvmlet** [comment]
Sure, I'll have a look at it. Meanwhile to unblock yourself you can force the version you want using gradles dependency resolution strategy configuration closure.

**Comment by crewmanmud** [comment]
Thanks - yes, this is on our radar to fix now so it may come to implementing your suggestion (as well as updating the version of the starter we're using).

For transparency sake, we're using version 2.1.5 of the starter - resulting in a particularly toxic mix of Netty version 4.1.29 (from `spring-boot-dependencies` BOM) and `io.grpc:netty` version 1.9.0 - the latter being compatible with Netty 4.1.17.Final (per doc link in OP).

**Comment by jvmlet** [comment]
It's better later  than never ;-)
