### ISSUE TITLE
I use an externally introduced properties resource file that does not take effect.

### ISSUE THREAD

**Issue by LiWenGu** [LogNet/grpc-spring-boot-starter#115]
I am using an externally imported resource file, but this grpc.port parameter does not take effect, but the server.port configuration information is in effect.
```properties
server.port=8071
grpc.port=50051
```
```java
@PropertySource(value={"file:/application.properties"})
public class FcwSpiderNotifyApplication {

    public static void main(String[] args) {
        SpringApplication.run(FcwSpiderNotifyApplication.class, args);
    }

}
```
```pom
<dependency>
            <groupId>io.github.lognet</groupId>
            <artifactId>grpc-spring-boot-starter</artifactId>
            <version>3.1.0</version>
</dependency>
```

**Comment by jvmlet** [comment]
Can't reproduce with `3.1.0`. What is the port that grpc server started on ?

**Comment by LiWenGu** [comment]
grpc server started on 6565

**Comment by jvmlet** [comment]
Can you please provide the repo that reproduces the issue ?

**Comment by LiWenGu** [comment]
this:  
[https://github.com/LiWenGu/LogNet_grpc-spring-boot-starter_115.git](url)

**Comment by jvmlet** [comment]
Thansk @LiWenGu , it's indeed reproducible with `3.1.0`.
Please upgrade  to `3.2.1` that fixes the issue ,I've verified it with your  sample.
