### ISSUE TITLE
 Use "compileOnly" configuration from gradle 2.13

### ISSUE THREAD

**Issue by otrosien** [LogNet/grpc-spring-boot-starter#12]
Motivation:
- gradle 2.13 introduced "compileOnly" for compiletime-only dependencies. 

Change: 
- remove springframework-propdeps plugin
- use compileOnly for "provided" and "optional" dependencies

Result:
- One less gradle plugin needed / more standard features in use

**Comment by jvmlet** [comment]
Closed via #13
