### ISSUE TITLE
Debug logging - How activate ?

### ISSUE THREAD

**Issue by chsi13** [LogNet/grpc-spring-boot-starter#121]
Hi. 

I want to see my gRPC requests logged in the console. So I run the service with environment variables GRPC_TRACE and GRPC_VERBOSITY... but no logs are showed...

Something more to do ??

__grpc version  : 1.19__

Thx.

**Comment by jvmlet** [comment]
These variables are only for `C-based` implementations ,see [this](https://stackoverflow.com/questions/37125975/how-to-debug-grpc-call)

**Comment by jvmlet** [comment]
Please see this [thread ](https://github.com/LogNet/grpc-spring-boot-starter/issues/110)

**Comment by chsi13** [comment]
I see solutions for c and go-based impl but nothing about java one? 

Thx

**Comment by jvmlet** [comment]
`GRPC_TRACE` and `GRPC_VERBOSITY` are for C-based. For java based please use `BinaryLog` as described [here](https://github.com/LogNet/grpc-spring-boot-starter/issues/110)  .
