### ISSUE TITLE
Support Springs @Ordered Annotation on GRpcServerRunner

### ISSUE THREAD

**Issue by MCLonips** [LogNet/grpc-spring-boot-starter#126]
I'm working with Spring Boots `CommandLineRunner` in my project to fill my application with some data after start. For that reason it is necessary to make a gRPC-Call. Your implementation of the `GRpcServerRunner` which is starting the gRPC-Server has the lowest order to be executed compared to all other `CommandLineRunner`. Without a working Server I am not able to make any gRPC-Calls after startup .

I did some research and found a Method to control the actual order of all `CommandLineRunner`
, Spring Boots `@Ordered`-Annotation. Is it possible to use it?

See my code-Snippet:
```
**
 * Hosts embedded gRPC server.
 */
@Slf4j
@Order(value = Ordered.HIGHEST_PRECEDENCE) //<-- Add this annotation
public class GRpcServerRunner implements CommandLineRunner, DisposableBean {
....
}
```

The value `HIGHEST_PRECEDENCE` forces Spring Boot to execute your runner directly after Startup. This would give me the opportunity to do some gRPC-Calls in my `Runner`.

**Comment by jvmlet** [comment]
I will check the order of servlet runner implemented by spring team and follow the same rules.
I would suggest you to add grpc server started event listener and execute your logic from there.

**Comment by jvmlet** [comment]
See `GRpcServerInitializedEvent`

**Comment by MCLonips** [comment]
Seems to work for me to subscribe on `ApplicationContext` to listen to `GRpcServerInitializedEvent`.
This also seems to be the correct way for my application thank you 👍 

Regardless you should think about the `@Order`-annotation to make sure gRPC-Server has the highest order and will be initialized first

**Comment by asinbow** [comment]
https://github.com/LogNet/grpc-spring-boot-starter/blob/f959ae4ba1e81232c2a56637f6ce27217009e564/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/GRpcServerRunner.java#L122

![image](https://user-images.githubusercontent.com/731874/86237398-45fbac00-bbce-11ea-9191-a155b4dbf859.png)

**Comment by jvmlet** [comment]
Controlled via  `grpc.start-up-phase` property
