### ISSUE TITLE
google.api.http Support

### ISSUE THREAD

**Issue by MilgoTest** [LogNet/grpc-spring-boot-starter#131]
Protobuf offers an option to create a REST api out of the box ([see here](https://grpc.io/blog/coreos/)). Is this option supported or is the support planned? 

I tried this example but there is no rest interface, neither with server.port nor with grpc.port.
```
syntax = "proto3";

package com.example;

import "google/api/annotations.proto";

option java_multiple_files = true;

message EchoMessage {
 string value = 1;
}

service EchoService {
  rpc Echo(EchoMessage) returns (EchoMessage) {
    option (google.api.http) = {
      post: "/v1/echo"
      body: "*"
    };
  }
}
```

**Comment by jvmlet** [comment]
You will need to integrate the [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway),  which is `go`-specific. Closing as this issue has nothing to do with the spring boot starter.
