### ISSUE TITLE
grpc-json-proxy integration

### ISSUE THREAD

**Issue by chsi13** [LogNet/grpc-spring-boot-starter#133]
Hi.

Would like to test grpc service through postman client.

I found this project : https://github.com/jnewmano/grpc-json-proxy

He talks about register a json codec on the grpc server.. How can I register that in the java implementation ?

**Comment by jvmlet** [comment]
It's better to ask him. I'm using https://github.com/uw-labs/bloomrpc

**Comment by jef** [comment]
I don't believe this is solvable by the tool, rather it's the implementation.

https://grpc.io/blog/grpc-with-json/
