### ISSUE TITLE
JWT auth implementation

### ISSUE THREAD

**Issue by majusko** [LogNet/grpc-spring-boot-starter#135]
Hi guys,

I created a simple Spring Boot Starter project implementing the JWT authentication and authorization. I'm extending this library developed by LogNet as I really love your project and don't have a need to create a new wheel.

Library link: https://github.com/majusko/grpc-jwt-spring-boot-starter

**Simple implementation** using custom annotation `@Allow(roles="admin")`
**Simple usage** showcase here: https://github.com/majusko/grpc-example/blob/master/src/main/kotlin/io/github/majusko/grpc/example/ServerExample.kt

Already using it in few production projects so the library will be definitely supported and I'm also open to contribution.

Would you consider mentioning this library in README? 
I'm open to a discussion if you like the library but imagine some other way of cooperation.

Mario

**Comment by jvmlet** [comment]
Please upgrade to `4.0.0`
