### ISSUE TITLE
Using tcp instead of grpc health check during consul registration

### ISSUE THREAD

**Issue by evk1986** [LogNet/grpc-spring-boot-starter#143]
When trying to register grpc server in consul recently was found that LogNet had not properly configured healthcheck. As a result we have service in consul, which doesn't have proper metadata and tags, health check route and so on. We use LogNet in prod, and we strongly need this functionality. 
From my point of view, the right way is to use [https://www.consul.io/docs/agent/checks.html ](url) grpc+inteval.
p.s. now LogNet use TCP+interval consul check.
If you @jvmlet  don't mind I will assign it to me and create PR shortly

**Comment by jvmlet** [comment]
Sure, please do

**Comment by jvmlet** [comment]
Closed by https://github.com/LogNet/grpc-spring-boot-starter/commit/2da3148e
