### ISSUE TITLE
Possibility of merge with yidongnan/grpc-spring-boot-starter?

### ISSUE THREAD

**Issue by donbeave** [LogNet/grpc-spring-boot-starter#144]
Hello, guys!

It's a nice project, but actually I have found another implementation: https://github.com/yidongnan/grpc-spring-boot-starter, which looks much more detailed with better documentation and much more features.

Have you ever considering to merge this project with another one and join force to develop features and fixing bugs?

We are just migrated from `io.github.lognet:grpc-spring-boot-starter` to `net.devh:grpc-spring-boot-starter`, because of some features, like health checks, metrics, tracing, etc... But we also found there is some fixes not implemented in yidongnan's version. It looks like his project has much more potential for future development.

I know it probably looks weird, but maybe it's time to start to think about merging these two projects into one?

**Comment by jvmlet** [comment]
@donbeave , I'll put that on my roadmap.

**Comment by deft1991** [comment]
And what did you decide?

**Comment by jvmlet** [comment]
@deft1991 , since then, all mentioned features have been implemented , if you are missing something -  staring discussion , opening feature request issues or PR is a good start.
