### ISSUE TITLE
Access Log

### ISSUE THREAD

**Issue by QeyCoder** [LogNet/grpc-spring-boot-starter#147]
I'm migrating my application to **grpc**. Everything working fine but for latency plotting I need access log in tomcat but I'm unable to generate access log. The only solution I found so far is the server interceptor. Doesn't **grpc** support access logging just like we have in tomcat if yes how to enable?

`127.0.0.1 - - [18/May/2020:13:06:28 +0530] "POST /app/api/v1.0/search HTTP/1.1" 200 1931396 1938`

**Comment by jvmlet** [comment]
Tomcat  ? grpc-server uses netty underneath by default and this is binary protocol.

**Comment by jvmlet** [comment]
FYI https://github.com/grpc/grpc-java/issues/1577 . Closing as not-related to this starter
