### ISSUE TITLE
GRPC Consul Discovery

### ISSUE THREAD

**Issue by QeyCoder** [LogNet/grpc-spring-boot-starter#148]
Did anybody use `grpc-spring-boot-starter` with consul as service discovery? 
I think there is a class `GrpcConsulRegistrar`.  But I'm confused about how to use that.

**Comment by jvmlet** [comment]
To integrate with Consul, all you need to do is to add `org.springframework.cloud:spring-cloud-starter-consul-discovery` dependency to your application.  See [this ](https://github.com/LogNet/grpc-spring-boot-starter#consul-integration)
