### ISSUE TITLE
Support bi-directional gRPC stream ?

### ISSUE THREAD

**Issue by junojuno90** [LogNet/grpc-spring-boot-starter#149]
Hi, thanks for good solution gRPC on java...
I have interest about bi-diriectional stream.

```
# some.proto
service SomeService {
    rpc streamSomething (stream SomeRequest) returns (stream SomeResponse);
}
```

Is this project also support bi-directional stream? 😃

**Comment by jvmlet** [comment]
This project supports everything that is supported by   grpc  library you use ;-) 
It helps you to get grpc server running with all your services (bi-directional, unary ect)

**Comment by jvmlet** [comment]
Added [demo ](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/main/java/org/lognet/springboot/grpc/demo/routeguide/RouteGuideService.java)+ [tests](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/demo/routeguide/RouteGuideDemo.java)
