### ISSUE TITLE
Is it possible to run rest controller along side gRPC server

### ISSUE THREAD

**Issue by sureshattaluri** [LogNet/grpc-spring-boot-starter#160]
I am just wondering if it is possible to run rest controller along side gRPC server setup using this starter.

**Comment by jvmlet** [comment]
yes, please see this test, it calls actuator endpoint   https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/DemoAppTest.java
