### ISSUE TITLE
Upgrade to Spring boot 2.3.4

### ISSUE THREAD

**Issue by iperminov** [LogNet/grpc-spring-boot-starter#161]
gRPC Spring boot starter currently depends on Spring boot 2.3.3. Unfortunately, Spring boot 2.3.3 contains a memory problem on Java 11+: spring-projects/spring-boot#22998 (full description in spring-projects/spring-boot#22991). This problem has been fixed in Spring boot 2.3.4.

Please, upgrade gRPC Spring boot starter to Spring boot 2.3.4.

**Comment by jvmlet** [comment]
The version of SP  your application is using depends only on version you defined in your build gradle/maven file. It's better to  use SP dependency plugin for you build system
