### ISSUE TITLE
Any way to use a grpc method as an RxJava observable?

### ISSUE THREAD

**Issue by parrotcar00** [LogNet/grpc-spring-boot-starter#163]
I have a simple use case of where I want to expose a RxJava observable through a stream method. I have code like:
`Observable<Mypojo> myPojoSource = Observable.just(myPojo);

        myPojoSource.subscribe(myPojo -> {

            //Here I want to call my Grpc method
            myGrpcMethod(myPojoe, responseObserver); //How do I get hold of this responseObserver variable?

        });`

But how do I get hold of that responseObserver variable? Is there anyway to get it?

**Comment by parrotcar00** [comment]
To give some more context, I have a pojo on my Grpc server that gets updated in a hard to predict fashion. So it seemed like best to use RxJava to assign a subscriber call back method to work with this pojo.
Now I want to expose this pojo through a Grpc stream returning method but I'm confused how to call the grpc stream stub from the observer callback?

**Comment by jvmlet** [comment]
Please have a look at test [in this commit](https://github.com/LogNet/grpc-spring-boot-starter/commit/0ef79fe586fbe1098edc8d92a15368b90b852f34)
