### ISSUE TITLE
support for spring security AuthenticationManager

### ISSUE THREAD

**Issue by swarupdonepudi** [LogNet/grpc-spring-boot-starter#167]
looks like it is not possible to add a custom authentication manager to the interceptor at this point which is needed to take advantage of "[Multitenancy Tenant by JWT Claim](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-multitenancy)" feature which is added in Spring Security 5.2.

currently AuthenticationManager is being added to securityInterceptor in [GrpcSecurity.java](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/security/GrpcSecurity.java#L73)

**Comment by jvmlet** [comment]
Hi @swarupdonepudi , sorry for late response. Are you after supporting multiple authorization servers ?

**Comment by jvmlet** [comment]
Unfortunately, [OAuth2ResourceServerConfigurer](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java) can work **only** with `HttpSecurity`, I can't reuse it  for `GrpcSecurity`. 
What you can do is to register your  own `CompositeJwtAuthenticationProvider`  with `JwtIssuerAuthenticationManagerResolver ` that selects target server based on passed  `Authentication` object:

```java

 @Override
    public void configure(GrpcSecurity builder) throws Exception {

 builder.authenticationProvider(new CompositeJwtAuthenticationProvider(new JwtIssuerAuthenticationManagerResolver(manager1,manager1)))
}
.....
class  CompositeJwtAuthenticationProvider implements AuthenticationProvider{
  public Authentication authenticate(Authentication authentication) throws AuthenticationException {
    return  resolver.select(authentication).authenticate(authentication);
 }
}
```

**Comment by swarupdonepudi** [comment]
@jvmlet yes i was trying to support multiple authorization servers but i realized that my auth design was not correct and i am now only using single authorization server. so, i am good for now. But thanks lot for your recommendation and insight. i will try it out if i need to support multiple authorization servers in the future. we can close this for now.
