### ISSUE TITLE
java.lang.ClassNotFoundException: io.grpc.protobuf.ProtoFileDescriptorSupplier

### ISSUE THREAD

**Issue by rohitranjan1991** [LogNet/grpc-spring-boot-starter#168]
I have a maven Spring boot 2.1.18 project setup and i have added the below dependency:

    <dependency>
        <groupId>io.github.lognet</groupId>
        <artifactId>grpc-spring-boot-starter</artifactId>
        <version>4.2.3</version>
    </dependency>

This is my service Code:

    @GRpcService
    class CustomGrpcService : GreeterGrpc.GreeterImplBase(){
        override fun sayHello(request: HelloRequest?, responseObserver: StreamObserver<HelloReply>?) {
            responseObserver!!.onNext(HelloReply.getDefaultInstance())
            responseObserver!!.onCompleted()
        }
    }

After starting the server i am getting the below error at the end:

    2020-12-03 19:11:56.182 rohit  INFO 60793 --- [           main] o.l.springboot.grpc.GRpcServerRunner     : Starting gRPC Server ...
    2020-12-03 19:11:56.193 rohit  INFO 60793 --- [           main] ConditionEvaluationReportLoggingListener : 

    Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
    2020-12-03 19:11:56.224 rohit  INFO 60793 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
     2020-12-03 19:11:56.622 rohit  INFO 60793 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
    2020-12-03 19:11:56.664 rohit  INFO 60793 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
    2020-12-03 19:11:56.739 rohit  INFO 60793 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
    2020-12-03 19:11:56.751 rohit  INFO 60793 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
    2020-12-03 19:11:56.752 rohit  INFO 60793 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
    2020-12-03 19:11:56.791 rohit  INFO 60793 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
    2020-12-03 19:11:56.793 rohit  INFO 60793 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
    2020-12-03 19:11:57.117 rohit  INFO 60793 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Shutdown ignored - container is not active already
    2020-12-03 19:11:57.117 rohit  INFO 60793 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Shutdown ignored - container is not active already
    2020-12-03 19:11:57.117 rohit  INFO 60793 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Shutdown ignored - container is not active already
    2020-12-03 19:11:57.117 rohit  INFO 60793 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
    2020-12-03 19:11:57.379 rohit  INFO 60793 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - 
    Shutdown initiated...
    2020-12-03 19:11:57.412 rohit  INFO 60793 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - 
    Shutdown completed.
    2020-12-03 19:11:57.464 rohit ERROR 60793 --- [           main] o.s.boot.SpringApplication               : Application run failed

    java.lang.NoClassDefFoundError: io/grpc/protobuf/ProtoFileDescriptorSupplier
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at io.grpc.health.v1.HealthGrpc.getServiceDescriptor(HealthGrpc.java:406)
	at io.grpc.health.v1.HealthGrpc$HealthImplBase.bindService(HealthGrpc.java:174)
	at io.grpc.internal.ServerImplBuilder.addService(ServerImplBuilder.java:131)
	at io.grpc.internal.ServerImplBuilder.addService(ServerImplBuilder.java:54)
	at io.grpc.internal.AbstractServerImplBuilder.addService(AbstractServerImplBuilder.java:84)
	at io.grpc.internal.AbstractServerImplBuilder.addService(AbstractServerImplBuilder.java:46)
	at org.lognet.springboot.grpc.GRpcServerRunner.run(GRpcServerRunner.java:69)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:781)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:319)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.groww.axis.application.AxisBankServiceApplicationKt.main(AxisBankServiceApplication.kt:28)
    Caused by: java.lang.ClassNotFoundException: io.grpc.protobuf.ProtoFileDescriptorSupplier
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 37 common frames omitted

Can someone suggest me what i might be doing wong ??

**Comment by jvmlet** [comment]
Can you show your dependency tree ?

**Comment by rohitranjan1991** [comment]
Sure. here you go.

com.myCompany.myProject:myProject-service:pom:1.0.0
+- com.fasterxml.jackson.module:jackson-module-kotlin:jar:2.9.9:compile
|  \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9.3:compile
+- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.3:compile
+- org.jetbrains.kotlin:kotlin-reflect:jar:1.4.20:compile
|  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.4.20:compile
|     \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.4.20:compile
+- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.4.20:compile
|  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.4.20:compile
+- io.springfox:springfox-swagger2:jar:2.9.2:compile
|  +- io.swagger:swagger-annotations:jar:1.5.20:compile
|  +- io.swagger:swagger-models:jar:1.5.20:compile
|  +- io.springfox:springfox-spi:jar:2.9.2:compile
|  |  \- io.springfox:springfox-core:jar:2.9.2:compile
|  +- io.springfox:springfox-schema:jar:2.9.2:compile
|  +- io.springfox:springfox-swagger-common:jar:2.9.2:compile
|  +- io.springfox:springfox-spring-web:jar:2.9.2:compile
|  +- com.google.guava:guava:jar:20.0:compile
|  +- com.fasterxml:classmate:jar:1.4.0:compile
|  +- org.slf4j:slf4j-api:jar:1.7.28:compile
|  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
|  |  +- org.springframework:spring-beans:jar:5.1.9.RELEASE:compile
|  |  +- org.springframework:spring-context:jar:5.1.9.RELEASE:compile
|  |  \- org.springframework:spring-aop:jar:5.1.9.RELEASE:compile
|  +- org.springframework.plugin:spring-plugin-metadata:jar:1.2.0.RELEASE:compile
|  \- org.mapstruct:mapstruct:jar:1.2.0.Final:compile
+- io.springfox:springfox-swagger-ui:jar:2.9.2:compile
+- org.springframework.boot:spring-boot-starter-data-jpa:jar:2.1.8.RELEASE:compile
|  +- org.springframework.boot:spring-boot-starter-aop:jar:2.1.8.RELEASE:compile
|  |  \- org.aspectj:aspectjweaver:jar:1.9.4:compile
|  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.1.8.RELEASE:compile
|  |  +- com.zaxxer:HikariCP:jar:3.2.0:compile
|  |  \- org.springframework:spring-jdbc:jar:5.1.9.RELEASE:compile
|  +- javax.transaction:javax.transaction-api:jar:1.3:compile
|  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
|  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
|  +- org.hibernate:hibernate-core:jar:5.3.11.Final:compile
|  |  +- javax.persistence:javax.persistence-api:jar:2.2:compile
|  |  +- org.javassist:javassist:jar:3.23.2-GA:compile
|  |  +- antlr:antlr:jar:2.7.7:compile
|  |  +- org.jboss:jandex:jar:2.0.5.Final:compile
|  |  +- org.dom4j:dom4j:jar:2.1.1:compile
|  |  \- org.hibernate.common:hibernate-commons-annotations:jar:5.0.4.Final:compile
|  +- org.springframework.data:spring-data-jpa:jar:2.1.10.RELEASE:compile
|  |  +- org.springframework:spring-orm:jar:5.1.9.RELEASE:compile
|  |  \- org.springframework:spring-tx:jar:5.1.9.RELEASE:compile
|  \- org.springframework:spring-aspects:jar:5.1.9.RELEASE:compile
+- org.springframework.boot:spring-boot-starter-web:jar:2.1.8.RELEASE:compile
|  +- org.springframework.boot:spring-boot-starter:jar:2.1.8.RELEASE:compile
|  |  +- org.springframework.boot:spring-boot:jar:2.1.8.RELEASE:compile
|  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.8.RELEASE:compile
|  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.1.8.RELEASE:compile
|  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.11.2:compile
|  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.28:compile
|  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
|  |  \- org.yaml:snakeyaml:jar:1.23:compile
|  +- org.springframework.boot:spring-boot-starter-json:jar:2.1.8.RELEASE:compile
|  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.9.9:compile
|  +- org.hibernate.validator:hibernate-validator:jar:6.0.17.Final:compile
|  |  \- javax.validation:validation-api:jar:2.0.1.Final:compile
|  +- org.springframework:spring-web:jar:5.1.9.RELEASE:compile
|  \- org.springframework:spring-webmvc:jar:5.1.9.RELEASE:compile
|     \- org.springframework:spring-expression:jar:5.1.9.RELEASE:compile
+- org.springframework.boot:spring-boot-starter-webflux:jar:2.1.8.RELEASE:compile
|  +- org.springframework.boot:spring-boot-starter-reactor-netty:jar:2.1.8.RELEASE:compile
|  |  \- io.projectreactor.netty:reactor-netty:jar:0.8.11.RELEASE:compile
|  |     \- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.39.Final:compile
|  |        \- io.netty:netty-transport-native-unix-common:jar:4.1.39.Final:compile
|  +- org.springframework:spring-webflux:jar:5.1.9.RELEASE:compile
|  \- org.synchronoss.cloud:nio-multipart-parser:jar:1.1.0:compile
|     \- org.synchronoss.cloud:nio-stream-storage:jar:1.1.3:compile
+- org.springframework.cloud:spring-cloud-starter-netflix-ribbon:jar:2.1.3.RELEASE:compile
|  +- org.springframework.cloud:spring-cloud-starter:jar:2.1.3.RELEASE:compile
|  |  +- org.springframework.cloud:spring-cloud-context:jar:2.1.3.RELEASE:compile
|  |  \- org.springframework.security:spring-security-rsa:jar:1.0.7.RELEASE:compile
|  |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.60:compile
|  |        \- org.bouncycastle:bcprov-jdk15on:jar:1.60:compile
|  +- org.springframework.cloud:spring-cloud-netflix-ribbon:jar:2.1.3.RELEASE:compile
|  |  \- org.springframework.cloud:spring-cloud-netflix-archaius:jar:2.1.3.RELEASE:compile
|  +- org.springframework.cloud:spring-cloud-starter-netflix-archaius:jar:2.1.3.RELEASE:compile
|  |  +- com.netflix.archaius:archaius-core:jar:0.7.6:compile
|  |  \- commons-configuration:commons-configuration:jar:1.8:compile
|  +- com.netflix.ribbon:ribbon:jar:2.3.0:compile
|  |  +- com.netflix.ribbon:ribbon-transport:jar:2.3.0:runtime
|  |  |  +- io.reactivex:rxnetty-contexts:jar:0.4.9:runtime
|  |  |  \- io.reactivex:rxnetty-servo:jar:0.4.9:runtime
|  |  +- com.netflix.hystrix:hystrix-core:jar:1.5.18:compile
|  |  +- javax.inject:javax.inject:jar:1:runtime
|  |  \- io.reactivex:rxnetty:jar:0.4.9:runtime
|  +- com.netflix.ribbon:ribbon-core:jar:2.3.0:compile
|  |  \- commons-lang:commons-lang:jar:2.6:compile
|  +- com.netflix.ribbon:ribbon-httpclient:jar:2.3.0:compile
|  |  +- commons-collections:commons-collections:jar:3.2.2:runtime
|  |  +- com.sun.jersey:jersey-client:jar:1.19.1:runtime
|  |  |  \- com.sun.jersey:jersey-core:jar:1.19.1:runtime
|  |  |     \- javax.ws.rs:jsr311-api:jar:1.1.1:runtime
|  |  +- com.sun.jersey.contribs:jersey-apache-client4:jar:1.19.1:runtime
|  |  +- com.netflix.servo:servo-core:jar:0.12.21:runtime
|  |  \- com.netflix.netflix-commons:netflix-commons-util:jar:0.3.0:runtime
|  +- com.netflix.ribbon:ribbon-loadbalancer:jar:2.3.0:compile
|  |  \- com.netflix.netflix-commons:netflix-statistics:jar:0.1.1:runtime
|  \- io.reactivex:rxjava:jar:1.3.8:compile
+- org.springframework.cloud:spring-cloud-starter-openfeign:jar:2.1.3.RELEASE:compile
|  +- org.springframework.cloud:spring-cloud-openfeign-core:jar:2.1.3.RELEASE:compile
|  +- org.springframework.cloud:spring-cloud-commons:jar:2.1.3.RELEASE:compile
|  +- io.github.openfeign:feign-core:jar:10.2.3:compile
|  +- io.github.openfeign:feign-slf4j:jar:10.2.3:compile
|  \- io.github.openfeign:feign-hystrix:jar:10.2.3:compile
+- org.redisson:redisson:jar:3.11.2:compile
|  +- io.netty:netty-common:jar:4.1.39.Final:compile
|  +- io.netty:netty-codec:jar:4.1.39.Final:compile
|  +- io.netty:netty-buffer:jar:4.1.39.Final:compile
|  +- io.netty:netty-transport:jar:4.1.39.Final:compile
|  |  \- io.netty:netty-resolver:jar:4.1.39.Final:compile
|  +- io.netty:netty-resolver-dns:jar:4.1.39.Final:compile
|  |  \- io.netty:netty-codec-dns:jar:4.1.39.Final:compile
|  +- io.netty:netty-handler:jar:4.1.39.Final:compile
|  +- javax.cache:cache-api:jar:1.1.1:compile
|  +- io.projectreactor:reactor-core:jar:3.2.12.RELEASE:compile
|  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
|  +- io.reactivex.rxjava2:rxjava:jar:2.2.12:compile
|  +- de.ruedigermoeller:fst:jar:2.57:compile
|  |  \- org.objenesis:objenesis:jar:2.5.1:compile
|  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.9:compile
|  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
|  +- net.bytebuddy:byte-buddy:jar:1.9.16:compile
|  \- org.jodd:jodd-bean:jar:5.0.10:compile
|     \- org.jodd:jodd-core:jar:5.0.10:compile
+- redis.clients:jedis:jar:2.9.0:compile
|  \- org.apache.commons:commons-pool2:jar:2.6.2:compile
+- com.myCompany.commons:myCompany-commons:jar:0.1.034-MYPROJECT-SNAPSHOT:compile
|  +- com.fasterxml.jackson.datatype:jackson-datatype-json-org:jar:2.9.9:compile
|  |  \- org.json:json:jar:20171018:compile
|  +- org.springframework.security:spring-security-crypto:jar:5.1.6.RELEASE:compile
|  +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.9.9:compile
|  |  \- joda-time:joda-time:jar:2.10.3:compile
|  +- org.apache.commons:commons-lang3:jar:3.8.1:compile
|  +- io.github.openfeign.form:feign-form-spring:jar:3.8.0:compile
|  |  +- io.github.openfeign.form:feign-form:jar:3.8.0:compile
|  |  \- commons-fileupload:commons-fileupload:jar:1.4:compile
|  |     \- commons-io:commons-io:jar:2.2:compile
|  +- com.sun.xml.bind:jaxb-core:jar:2.3.0:compile
|  +- com.sun.xml.bind:jaxb-impl:jar:2.3.0:compile
|  +- org.springframework.session:spring-session:jar:1.3.5.RELEASE:compile
|  |  \- commons-logging:commons-logging:jar:1.2:compile
|  +- org.springframework.data:spring-data-commons:jar:2.1.10.RELEASE:compile
|  +- org.jetbrains:annotations:jar:16.0.1:compile
|  +- net.logstash.logback:logstash-logback-encoder:jar:6.1:compile
|  \- org.apache.commons:commons-text:jar:1.8:compile
+- com.myCompany.logger:myCompany-logger:jar:1.0.2-SNAPSHOT:compile
|  +- io.vertx:vertx-core:jar:3.9.4:compile
|  |  +- io.netty:netty-handler-proxy:jar:4.1.39.Final:compile
|  |  |  \- io.netty:netty-codec-socks:jar:4.1.39.Final:compile
|  |  +- io.netty:netty-codec-http:jar:4.1.39.Final:compile
|  |  \- io.netty:netty-codec-http2:jar:4.1.39.Final:compile
|  +- org.apache.logging.log4j:log4j-api:jar:2.11.2:compile
|  +- org.apache.logging.log4j:log4j-core:jar:2.11.2:compile
|  +- ch.qos.logback:logback-core:jar:1.2.3:compile
|  \- ch.qos.logback:logback-classic:jar:1.2.3:compile
+- com.myCompany.grpc:myCompany-grpc-client:jar:1.0-SNAPSHOT:compile
|  +- com.google.protobuf:protobuf-java:jar:3.14.0:compile
|  \- io.grpc:grpc-stub:jar:1.34.0:compile
+- org.springframework.boot:spring-boot-starter-data-redis:jar:1.5.18.RELEASE:compile
|  \- org.springframework.data:spring-data-redis:jar:2.1.10.RELEASE:compile
|     +- org.springframework.data:spring-data-keyvalue:jar:2.1.10.RELEASE:compile
|     +- org.springframework:spring-oxm:jar:5.1.9.RELEASE:compile
|     \- org.springframework:spring-context-support:jar:5.1.9.RELEASE:compile
+- io.micrometer:micrometer-core:jar:1.1.6:compile
|  +- org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
|  \- org.latencyutils:LatencyUtils:jar:2.0.3:compile
+- io.micrometer:micrometer-registry-prometheus:jar:1.1.6:compile
|  \- io.prometheus:simpleclient_common:jar:0.5.0:compile
|     \- io.prometheus:simpleclient:jar:0.5.0:compile
+- org.springframework.boot:spring-boot-starter-amqp:jar:2.1.8.RELEASE:compile
|  +- org.springframework:spring-messaging:jar:5.1.9.RELEASE:compile
|  \- org.springframework.amqp:spring-rabbit:jar:2.1.8.RELEASE:compile
|     +- org.springframework.amqp:spring-amqp:jar:2.1.8.RELEASE:compile
|     |  \- org.springframework.retry:spring-retry:jar:1.2.4.RELEASE:compile
|     \- com.rabbitmq:amqp-client:jar:5.4.3:compile
+- org.springframework.boot:spring-boot-starter-undertow:jar:2.1.8.RELEASE:compile
|  +- io.undertow:undertow-core:jar:2.0.26.Final:compile
|  |  +- org.jboss.xnio:xnio-api:jar:3.3.8.Final:compile
|  |  \- org.jboss.xnio:xnio-nio:jar:3.3.8.Final:runtime
|  +- io.undertow:undertow-servlet:jar:2.0.26.Final:compile
|  |  \- org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:jar:1.0.2.Final:compile
|  +- io.undertow:undertow-websockets-jsr:jar:2.0.26.Final:compile
|  |  \- org.jboss.spec.javax.websocket:jboss-websocket-api_1.1_spec:jar:1.1.4.Final:compile
|  +- javax.servlet:javax.servlet-api:jar:4.0.1:compile
|  \- org.glassfish:javax.el:jar:3.0.0:compile
+- org.springframework.boot:spring-boot-starter-actuator:jar:2.1.8.RELEASE:compile
|  \- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.1.8.RELEASE:compile
|     \- org.springframework.boot:spring-boot-actuator:jar:2.1.8.RELEASE:compile
+- mysql:mysql-connector-java:jar:8.0.17:runtime
+- org.springframework.boot:spring-boot-starter-test:jar:2.1.8.RELEASE:test
|  +- org.springframework.boot:spring-boot-test:jar:2.1.8.RELEASE:test
|  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.1.8.RELEASE:test
|  +- com.jayway.jsonpath:json-path:jar:2.4.0:test
|  |  \- net.minidev:json-smart:jar:2.3:test
|  |     \- net.minidev:accessors-smart:jar:1.2:test
|  |        \- org.ow2.asm:asm:jar:5.0.4:test
|  +- junit:junit:jar:4.12:test
|  +- org.assertj:assertj-core:jar:3.11.1:test
|  +- org.mockito:mockito-core:jar:2.23.4:test
|  |  \- net.bytebuddy:byte-buddy-agent:jar:1.9.16:test
|  +- org.hamcrest:hamcrest-core:jar:1.3:test
|  +- org.hamcrest:hamcrest-library:jar:1.3:test
|  +- org.skyscreamer:jsonassert:jar:1.5.0:test
|  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
|  +- org.springframework:spring-core:jar:5.1.9.RELEASE:compile
|  |  \- org.springframework:spring-jcl:jar:5.1.9.RELEASE:compile
|  +- org.springframework:spring-test:jar:5.1.9.RELEASE:test
|  \- org.xmlunit:xmlunit-core:jar:2.6.3:test
+- io.projectreactor:reactor-test:jar:3.2.12.RELEASE:test
+- io.github.openfeign:feign-okhttp:jar:11.0:compile
|  \- com.squareup.okhttp3:okhttp:jar:3.8.1:compile
|     \- com.squareup.okio:okio:jar:1.13.0:compile
+- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.9:compile
+- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.9:compile
+- org.hibernate:hibernate-envers:jar:5.3.11.Final:compile
|  \- org.jboss.logging:jboss-logging:jar:3.3.3.Final:compile
+- com.github.ulisesbocchio:jasypt-spring-boot-starter:jar:2.0.0:compile
|  \- com.github.ulisesbocchio:jasypt-spring-boot:jar:2.0.0:compile
|     \- org.jasypt:jasypt:jar:1.9.2:compile
+- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
+- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
|  \- commons-codec:commons-codec:jar:1.11:compile
+- io.github.openfeign:feign-httpclient:jar:11.0:compile
+- io.github.lognet:grpc-spring-boot-starter:jar:4.2.3:compile
|  +- io.grpc:grpc-netty-shaded:jar:1.33.1:compile
|  |  \- io.grpc:grpc-core:jar:1.33.1:compile (version selected from constraint [1.33.1,1.33.1])
|  |     +- io.grpc:grpc-api:jar:1.33.1:compile (version selected from constraint [1.33.1,1.33.1])
|  |     |  \- io.grpc:grpc-context:jar:1.33.1:compile
|  |     +- com.google.code.gson:gson:jar:2.8.5:runtime
|  |     +- com.google.android:annotations:jar:4.1.1.4:runtime
|  |     \- io.perfmark:perfmark-api:jar:0.19.0:runtime
|  +- io.grpc:grpc-services:jar:1.33.1:compile
|  |  \- com.google.protobuf:protobuf-java-util:jar:3.12.0:runtime
|  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.25.Final:compile
\- io.grpc:grpc-protobuf:jar:1.34.0:compile
   +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
   +- com.google.api.grpc:proto-google-common-protos:jar:1.16.0:compile
   +- io.grpc:grpc-protobuf-lite:jar:1.34.0:compile
   +- com.google.errorprone:error_prone_annotations:jar:2.3.4:compile
   \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.18:runtime

**Comment by jvmlet** [comment]
io.grpc:grpc-protobuf:jar:1.34.0
It should be 1.33. Did you import it manually?

**Comment by rohitranjan1991** [comment]
Yeah, I added it manually. i have now removed it and the server has started successfully. Thanks a lot for responding so quickly :-)
