### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/validation/Validator

### ISSUE THREAD

**Issue by heowc** [LogNet/grpc-spring-boot-starter#169]
I had that problem while changing grpc-spring-boot-starter to version 4.3.0. This seems to have been added [here](https://github.com/LogNet/grpc-spring-boot-starter/commit/defbc8000bebd1cfdbc7eb4d399bfa9bac00cc59), and I think it's a problem as users cannot use it selectively. I get an [error in the CI](https://github.com/heowc/SpringBootSample/runs/1586496068?check_suite_focus=true#step:9:322) of my repository.

See https://github.com/heowc/SpringBootSample/pull/329

**Comment by jvmlet** [comment]
Thanks for pointing out. Fixed in `4.3.1`, please upgrade.

**Comment by heowc** [comment]
Could you reopen this issue until you fix it? I think this may be useful for other users. 😆

**Comment by jvmlet** [comment]
It's fixed in `4.3.1`

**Comment by jvmlet** [comment]
Unless you are saying  it's reproducible it with `4.3.1` :-)

**Comment by heowc** [comment]
Oops... Thank you so much 👍
