### ISSUE TITLE
Upgrading from 3.x.x to 4.x.x breaks without Spring Security

### ISSUE THREAD

**Issue by paulius-p** [LogNet/grpc-spring-boot-starter#173]
When upgrading a project which does not use any spring security and has dependencies related to it, the project fails to start-up due to unsatisfied dependencies for security, though nothing is configured or used.
Is seems now you need to explicitly disable spring security autoconfiguration in order for it to work:
```
@SpringBootApplication(exclude = {
    org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration.class,
    org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration.class}
)
```

Ideally you shouldn't need to do that I think.

**Comment by jvmlet** [comment]
Can please elaborate more on `project which does not use any spring security and has dependencies related to it` ?

**Comment by paulius-p** [comment]
Project does not use `@EnableWebSecurity` or any security annotations, but has 
```
spring-boot-actuator-autoconfigure
spring-security-config
spring-security-core
```
from transitive dependencies

**Comment by jvmlet** [comment]
Do you suspect that this  grpc starter triggered the creation of `org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityConfigurerAdapter` bean ? 
Are you migrating  Spring Boot  version as well ?

**Comment by paulius-p** [comment]
Yes, it happened when I've bumped this starter's version and grpc.

I've created a minimal project replicating this - https://github.com/paulius-p/grpc-spring-starter-error-example
It seems this happens because of the specific dependencies in the project, so not entirely sure if it's because if this module or because of something else. Just that with the old version it worked alright.

**Comment by jvmlet** [comment]
With which spring boot version it used to work fine (when you were using 3.x version of grpc starter) ?

**Comment by jvmlet** [comment]
Works  as expected with Spring Boot  `2.4.0`, please rename to `patch.patch` and apply tp your  [repo ](https://github.com/paulius-p/grpc-spring-starter-error-example)
[patch.txt](https://github.com/LogNet/grpc-spring-boot-starter/files/5753803/patch.txt)

**Comment by paulius-p** [comment]
Thanks, that fixed it.
