### ISSUE TITLE
How to monitor multiple ports

### ISSUE THREAD

**Issue by pyeno** [LogNet/grpc-spring-boot-starter#174]
I want to be able to distinguish the ports exposed by intranet services and extranet services. How can this be done?

**Comment by jvmlet** [comment]
you mean you wan to have `ip` tag on micrometers' `timer` ?

**Comment by jvmlet** [comment]
Please try with `4.4.1-SNAPSHOT` by adding  `maven { url "https://oss.sonatype.org/content/repositories/snapshots" }` repository.
I'll release `4.4.1`  once you confirm it's working as expected

**Comment by jojoti** [comment]
Sorry, now I want to upgrade the version of grpc starter. The previous issue solved a part of the problem of external and internal calls of a server frontend process, but @GRpcService could not distinguish their respective entrances. In other words, the required internal cluster traffic and External traffic including grpc BindableService needs to be deployed separately. This is the case when building a grpc service in golang. We use two ports to distinguish between terminal call traffic and cluster call traffic. The user terminal, such as the traffic sent by js client using grpc, needs to be separated from the internal traffic of the cluster.
