### ISSUE TITLE
Support simple Authorization header for debugging purposes

### ISSUE THREAD

**Issue by jvmlet** [LogNet/grpc-spring-boot-starter#178]

**Comment by jvmlet** [comment]
@tobq, FYI

**Comment by tobq** [comment]
@jvmlet This isn't only for debugging. GRPC is cross-platform, and the standard header used for Authorization is... Authorization. spring-boot-starter may provide an abstraction for this access token key between other spring boot apps (using the static `KEY`), but many other types of apps / existing GRPC clients/services use the `Authorization` key. Is there a specific reason this project decided to diverge from this convention? I think this unconventional `Authorization-bin` key should at least be documented somewhere - i.e. the readme

**Comment by jvmlet** [comment]
There is no GRPC standard header to carry authorization claim. `Autherization` is mostly used as HTTP analog. 
Readme does contain (already) the documentation about how to configure the  client. Server looks both for `Autherization` and `Autherization-bin`.The reason I chose the binary format is to at least not to send clear username:password.

**Comment by tobq** [comment]
@jvmlet I see info regarding clients created in java. Is this security only compatible with other grpc-spring-boot-starter services? README says `When false, the authentication header is sent with Authentication key using ASCII marshaller.` but from my testing, the `Authorization` header is never used. Also this may be related to the issue I'm running into ATM https://github.com/LogNet/grpc-spring-boot-starter/issues/184

**Comment by tobq** [comment]
Indeed it only checks for the binary header `grpc-spring-boot-starter-4.4.2-sources.jar!/org/lognet/springboot/grpc/security/SecurityInterceptor.java:48`

**Comment by tobq** [comment]
It looks like the implementation recently changed, I'll update to the latest version: https://github.com/LogNet/grpc-spring-boot-starter/blob/52f4ff78ea4681a6f71beabe1dabd1916a00dc5b/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/security/SecurityInterceptor.java#L57

**Comment by tobq** [comment]
Is this available in some form of nightly build? Latest maven package doesn't contain the change

**Comment by tobq** [comment]
@jvmlet Do you have an ETA for this being published to maven?

**Comment by jvmlet** [comment]
#178 was released in `4.4.3` 1  week  ago https://github.com/LogNet/grpc-spring-boot-starter/releases/tag/v.4.4.3
