### ISSUE TITLE
how to access /actuator/metrics endpoint?

### ISSUE THREAD

**Issue by swarupdonepudi** [LogNet/grpc-spring-boot-starter#183]
i am trying to setup micrometer prometheus integration. in order to configure prometheus to scrape metrics we would need an http endpoint to be exposed by the server. I am not sure how to get that endpoint when using this starter.

**Comment by jvmlet** [comment]
I see 2 options to support Prometheus  integration :

* Long and innovative : We reach out Prometheus team advising to  consider  making scrapping using gRPC , developing   `proto` file with RPC API  (methods, requests, response) as `the Prometheus   gRPC standard`  in addition the their REST contract.

*  Short :  start by adding `web` starter to your project. If standard actuator endpoint doesn't contain gRPC metrics, I'll fix it

**Comment by jvmlet** [comment]
@swarupdonepudi , you can also  use [Prometheus pushgateway](https://github.com/prometheus/pushgateway)

**Comment by swarupdonepudi** [comment]
ok will try those options. thanks.

**Comment by jvmlet** [comment]
[Proposal ](https://github.com/prometheus/prometheus/issues/8414)

**Comment by jvmlet** [comment]
See [demo ](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/DemoAppTest.java)

**Comment by jvmlet** [comment]
[Docs](https://github.com/LogNet/grpc-spring-boot-starter#442-exposing-prometheus-endpoint)
