### ISSUE TITLE
@LocalRunningGrpcPort with Kotlin

### ISSUE THREAD

**Issue by obvionaoe** [LogNet/grpc-spring-boot-starter#186]
Hi, I'm trying to test my server written in Kotlin, but when I try to get the port where the server is running through the annotation it never injects it!

I've tried these ways:
```kotlin
// I get "kotlin.UninitializedPropertyAccessException: lateinit property PORT has not been initialized"
@LocalRunningGrpcPort
private lateinit var PORT: Integer

------------------------------------------------

// default value is always used because the annotation never injects
@LocalRunningGrpcPort
private var PORT = 6565
```

What am I doing wrong? How can I get this to work?

Thanks

**Comment by jvmlet** [comment]
The class that has this attribute should be spring bean. Is it?

**Comment by obvionaoe** [comment]
It's a @Component

**Comment by jvmlet** [comment]
Are you sure it's instantiated via spring factory?

**Comment by obvionaoe** [comment]
How do I check for that? I'm still not very fluent with some of Spring's concepts :slightly_frowning_face:

**Comment by jvmlet** [comment]
If you don't call its constructor by yourself then it's instantiated by spring.

**Comment by obvionaoe** [comment]
I try to Autowire it but I get Unsatisfied Dependency Exception

**Comment by jvmlet** [comment]
Please post your code snippets

**Comment by o-shevchenko** [comment]
I faced the same issue.
This is the code:
```kotlin
@Configuration
class GrpcClientConfig{

    @LocalRunningGrpcPort
    private val port: Int = 1234
    @Bean
    fun browserServiceStub(): BrowserServiceGrpc.BrowserServiceBlockingStub {
        val managedChannel = ManagedChannelBuilder.forAddress("0.0.0.0", port)
            .enableRetry()
            .usePlaintext()
            .build()
        return BrowserServiceGrpc.newBlockingStub(managedChannel)
    }
}
...
@Component
class BrowserGrpcClient(@Autowired private val service: BrowserServiceGrpc.BrowserServiceBlockingStub) {
...
}
```

**Comment by jvmlet** [comment]
@o-shevchenko , same test fails in java as well.
Looks like spring-test initializes test dependent  beans before `autoconfiguration`  
Refactor you test to have port  injected  directly to test class:


```kotlin
@SpringBootTest
class BrowserGrpcServiceTest {
    @LocalRunningGrpcPort
    private val port: Int = 1234
}

```

**Comment by o-shevchenko** [comment]
Thanks @jvmlet for the answer. @LocalRunningGrpcPort works inside @SpringBootTest. I can workaround such an issue.
But I would like to make tests for flexible and inject my client to tests and don't create services and channels everywhere.

**Comment by o-shevchenko** [comment]
@LocalRunningGrpcPort is available only inside @Test. SO, each test should look like 
```kotlin
@Test
    fun `my test`() {
        val managedChannel = ManagedChannelBuilder.forAddress("0.0.0.0", port)
            .enableRetry()
            .usePlaintext()
            .build()
        val service = BrowserServiceGrpc.newBlockingStub(managedChannel)
        val client = BrowserGrpcClient(service)
        
        // TODO
    }
```

That's not really convenient

**Comment by jvmlet** [comment]
You can do the technique described [here](https://jira.devtools.intel.com/projects/TWC195/issues/TWC195-1103?filter=myopenissues) with `GRpcServerInitializedEvent`.
Btw, I wounder if vanilla spring `@Value("${server.port}") int port`  works in your test setup  that fails to  inject `@LocalRunningGrpcPort`

**Comment by o-shevchenko** [comment]
We currently use @Value("${grpc.port}") to use static port for tests. But we have a couple of Grpc services, and we have to set a unique port for each of them in tests. That's not really good solution, so we want to use a random port (grpc.port=0) but faced the problem with @LocalRunningGrpcPort.

**Comment by o-shevchenko** [comment]
No, @Value("${server.port}") just returns a port from a configuration file. If we set `0` it will return `0` but not random port.
But our beans can be initialized, that's what we currently use. 
```kotlin
@Configuration
class GrpcClientConfig(
    @Value("\${grpc.port}") private val port: Int
) {

    @Bean
    fun browserServiceStub(): BrowserServiceGrpc.BrowserServiceBlockingStub {
        val managedChannel = ManagedChannelBuilder.forAddress("0.0.0.0", port)
            .enableRetry()
            .usePlaintext()
            .build()
        return BrowserServiceGrpc.newBlockingStub(managedChannel)
    }
}
```

**Comment by jvmlet** [comment]
So `@Value("${server.port}")`  also doesn't work when injected into configuration and not into test. The difference is that it's populated with 0 and not null, which is even worth.
Have you tried to initialize your client from grpc server started event in your test cfg?

**Comment by o-shevchenko** [comment]
No, sorry for confusing you. @Value("${server.port}") works fine even if we invoke it in the configuration. But it's just read port from application.yaml.

```kotlin
@Configuration
class GrpcClientConfig(
    @Value("\${grpc.port}") private val port: Int
) {

    @Bean
    fun browserServiceStub(): BrowserServiceGrpc.BrowserServiceBlockingStub {
        val managedChannel = ManagedChannelBuilder.forAddress("0.0.0.0", port)
            .enableRetry()
            .usePlaintext()
            .build()
        return BrowserServiceGrpc.newBlockingStub(managedChannel)
    }
}
```
That code works fine ^^^

**Comment by jvmlet** [comment]
Tried this approach?
https://www.baeldung.com/spring-boot-running-port#2-handling-servletwebserverinitializedevent

**Comment by o-shevchenko** [comment]
I have just tried it. It didn't help. It doesn't work for configuration and it makes no sense to use it in `@Test` since `@LocalRunningGrpcPort` works there anyway.
