### ISSUE TITLE
How to add custom tag to the MonitoringServerInterceptor?

### ISSUE THREAD

**Issue by simonwu-sn** [LogNet/grpc-spring-boot-starter#191]
Is there anything similar with WebMvcTagsContributor?

**Comment by jvmlet** [comment]
Yes, you should be able to do this with tag filter. Will post sample at Sunday

**Comment by simonwu-sn** [comment]
Thanks. Looking forward to it.

**Comment by simonwu-sn** [comment]
Hi hamlet, sorry to bother you again. Could you share how we can do it by tag filter? Thanks.

**Comment by jvmlet** [comment]
@simonwu-sn ,  with `4.4.5-SNAPSHOT` you can add custom tags by defining `GRpcMetricsTagsContributor` bean in your app context.
For unary  calls - `RequestAwareGRpcMetricsTagsContributor` bean .
Demo is [here](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/GrpcMeterTest.java)

Please provide your feedback,  readme will be updated later

**Comment by jvmlet** [comment]
`4.4.5` was released

**Comment by simonwu-sn** [comment]
Great, I will try it.
And I only use it for unary call.

**Comment by simonwu-sn** [comment]
It works, thanks a lot!
