### ISSUE TITLE
How to integrate Spring-Boot-Actuator endpoints and GRPC together?

### ISSUE THREAD

**Issue by Joholland** [LogNet/grpc-spring-boot-starter#2]
It doesn't look like you can have them spin up say, jetty for the actuator endpoints and the embedded GRPC server together. The GRPC one takes over.

**Comment by jvmlet** [comment]
You are right, I haven't found the API to attach gRPC listener to the running instance of server.
At our own projects we are running both embedded Tomcat that hosts actuator endpoints and embedded gRPC server on different ports.

**Comment by Joholland** [comment]
I tried this, but I didn't see the Jetty instance start. I can try embedded tomcat. Did you do anything else to make this side by side configuration work?

**Comment by jvmlet** [comment]
@Joholland,
I've updated the demo application to host actuators + added test case for this.
Also, you can start demo app with `gradle bootRun` or `java -jar grpc-spring-boot-starter-demo-0.0.2.jar` and see the output of  `http://localhost:8080/env`.

**Comment by axcrest** [comment]
@jvmlet does your solution get the actuator to give info on GRPC such as tracing the request time of those GRPC endpoints?  I want to know how long my business logic is taking to respond, and the logic is triggered by the GRPC endpoints.

**Comment by jvmlet** [comment]
@axcrest not yet, but you can have a loot at 
 https://github.com/LogNet/grpc-spring-boot-starter/issues/136 that integrates kibana APM via interceptors support as example

**Comment by jvmlet** [comment]
I have plans to expose metrics via micrometer.io, so stay tuned 😁

**Comment by petrmac** [comment]
@jvmlet, we are using the grpc-spring-boot-starter, but would like to run boot alongside to provide the kubernetes liveness and readiness probes. The boot however does not start web server (neither Tomcat, nor Jetty). 
Would you have any hint on how to use spring boot actuator on http (rest) for health check alongside the grpc port?

**Comment by jvmlet** [comment]
If you add web and actuator starters to your app, do you see metrics exposed by grpc?
