### ISSUE TITLE
grpc-netty dependency support

### ISSUE THREAD

**Issue by oburgosm** [LogNet/grpc-spring-boot-starter#203]
I'm currently using LogNet/grpc-spring-boot-starter at version 3.5.7 and I'm trying to update to 4.4.5, but I have a problem due to use of grpc-netty-shaded, that it is the only one option since version 4.2.1 (#108).

I have an application with several components and I need to reuse boosEventLoop and workersEventLoopGroup between this components (for example, webflux), but I can't do it with latest version because my shared EventLoopGroup is not an instance of of `io.grpc.netty.shaded.io.netty.channel.EventLoopGroup`

How could I do it? 

I think that it would fine if there was the possibility to switch between grpc-netty-shaded and grpc-netty

**Comment by jvmlet** [comment]
Can you try to exclude netty shaded  transitive dependencies from starter's dependencies and include yours instead?

**Comment by oburgosm** [comment]
I tried, but I get a `ClassNotFoundException: io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder`.

It seems that `org.lognet.springboot.grpc.autoconfigure.GRpcAutoConfiguration` need it

**Comment by jvmlet** [comment]
Yes.. Will need to support such mode, sorry

**Comment by jvmlet** [comment]
As a second thought,  repackaging is meant to solve the problem when the underlying library uses **THAT** specific dependency version,  _repackaged_  !!!, giving you the possibility to bring another version of the same library  and don't break  the compatibility between the starter and  the dependency it was compiled and tested with. 
There are plenty of components that come with repackaged  `guava` for example (they are known to be not so backward compatible) but this doesn't mean that in my app I can't use the latest and greatest guava version.
Relying on user to include the right `netty` version will produce more issues like [this](https://github.com/LogNet/grpc-spring-boot-starter/issues/200)
If you are instantiating and manage the `EventLoopGroup` instance by yourself nothing stops you from including the `netty` version of  your choice and use `io.netty.channel` package in you app.
Can you please try this ?

**Comment by oburgosm** [comment]
I'm not sure what you're proposing. What exactly do you want me to try?

Anyway, I understand that using of grpc-netty-shaded should be the default option for the reasons you commented, but not the only one, I think.

**Comment by jvmlet** [comment]
Add the `netty` library to you app and use  classes from  `io.netty.channel` package

**Comment by oburgosm** [comment]
I tried it , but it does not  work, as I commented previously.

**Comment by jvmlet** [comment]
I mean you should NOT exclude `shaded`, just add  `netty` in addition

**Comment by jvmlet** [comment]
can you please paste the snippet how do  you get hold of  `eventLoop` ?

**Comment by oburgosm** [comment]
Yes, I tried without exclude `shaded` dependency too, and it doesn't work

I have a `GRpcServerBuilderConfigurer` bean in which I inject my shared EventLoopGroup.

```
public class GrpcServerSocket extends GRpcServerBuilderConfigurer {

    private io.netty.channel.EventLoopGroup bossEventLoopGroup;


    public GrpcServerSocket(final io.netty.channel.EventLoopGroup bossEventLoopGroup ) {
         this.bossEventLoopGroup = bossEventLoopGroup;
    }

    @Override
    public void configure(final ServerBuilder<?> serverBuilder) {
        nettyServerBuilder.bossEventLoopGroup(this.bossEventLoopGroup);
    }
}
```

**Comment by jvmlet** [comment]
Can you please try with  `4.4.7-SNAPSHOT` (requires SB `2.4.5`) once [build ](https://travis-ci.org/github/LogNet/grpc-spring-boot-starter/builds/768820101) finishes. Don't forget to  add repo
```
maven { url "https://oss.sonatype.org/content/repositories/snapshots" } //for snashot builds
```

**Comment by jvmlet** [comment]
[This build ](https://travis-ci.org/github/LogNet/grpc-spring-boot-starter/builds/768820599 ), sorry

**Comment by oburgosm** [comment]
It's works for me! Thanks you!

**Comment by jvmlet** [comment]
👍 Will release `4.4.7` soon

**Comment by jvmlet** [comment]
`4.4.7`  released

**Comment by larrywest42** [comment]
For anyone else arriving here, if you get _(white-space added)_:

```
⋮
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: 
    Invalid bean definition with name 'nettyServerBuilder' defined in class path resource 
        [org/lognet/springboot/grpc/autoconfigure/ShadedNettyConfiguration.class]: 
            Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; 
                factoryBeanName=org.lognet.springboot.grpc.autoconfigure.ShadedNettyConfiguration; factoryMethodName=nettyServerBuilder; initMethodName=null; destroyMethodName=(inferred);
                defined in class path resource [org/lognet/springboot/grpc/autoconfigure/ShadedNettyConfiguration.class]] for bean 'nettyServerBuilder': 
            There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; 
                factoryBeanName=org.lognet.springboot.grpc.autoconfigure.PureNettyConfiguration; factoryMethodName=nettyServerBuilder; initMethodName=null; destroyMethodName=(inferred); 
                defined in class path resource [org/lognet/springboot/grpc/autoconfigure/PureNettyConfiguration.class]] bound.
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:995)
⋮
```

...and can't update to [4.5.2](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/ReleaseNotes.md#version-452) or [later](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/ReleaseNotes.md#version-452) to address this issue (#214) in 4.4.7, and you don't choose to allow multiple bean definitions (`spring.main.allow-bean-definition-overriding=true` — generally a bad idea as it's a global setting), you'll need to do either:

```xml
   <exclusions>
        <exclusion>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
        </exclusion>
   </exclusions>
```

or

```xml
   <exclusions>
        <exclusion>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty</artifactId>
        </exclusion>
   </exclusions>
```

CC @jvmlet

**Comment by jvmlet** [comment]
@larrywest42, what stops you from upgrading to the latest version?
