### ISSUE TITLE
Is there a way to make an existing ServerInterceptor global?

### ISSUE THREAD

**Issue by dimi-nk** [LogNet/grpc-spring-boot-starter#207]
If a `ServerInterceptor` `@Bean` which is out of our control is already provided, is there a way to promote it to a global server interceptor (e.g. programmatically)? I wanted to avoid:

- defining the bean in each server, e.g. `@GRpcService(interceptors = { MyServerInterceptor.class })`
- re-providing the `@Bean` since it'll exist in the context twice, e.g.

```java
@Bean
@GRpcGlobalInterceptor
public MyServerInterceptor myGlobalServerInterceptor(MyServerInterceptor interceptor) {
  return interceptor;
}
```

**Comment by jvmlet** [comment]
Can you try to achieve this with meta annotation  ?

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.TYPE, ElementType.METHOD })
@Documented
@GRpcService(interceptors = { MyServerInterceptor.class })
public @interface MyGrpcServiceWithGlobalInterceptor{
}

@MyGrpcServiceWithGlobalInterceptor
public class MyService{
}
```

**Comment by jvmlet** [comment]
@dimi-nk , does this answer your question ?

**Comment by dimi-nk** [comment]
@jvmlet yes! the second solution works just fine :) thanks for the help
