### ISSUE TITLE
Running newest version without allow-bean-definition-overriding=true as a spring property

### ISSUE THREAD

**Issue by mortenlocka** [LogNet/grpc-spring-boot-starter#208]
Hi, 

We haven't enabled the "allow-bean-definition-overriding" property in our project. The application fails to load the applicationContext with the newest version. 

`: Invalid bean definition with name ‘nettyServerBuilder’ defined in class path resource [org/lognet/springboot/grpc/autoconfigure/ShadedNettyConfiguration.class] ... There is already defined in class path resource [org/lognet/springboot/grpc/autoconfigure/PureNettyConfiguration.class.`

Ref https://github.com/LogNet/grpc-spring-boot-starter/blob/cc33050833f7f0decf461b8bc79e53e9bd489725/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/autoconfigure/GRpcAutoConfiguration.java#L40

Any chance for a rewrite? Instead of using the bean-def-overriding mechanism? 

Thanks!

**Comment by jvmlet** [comment]
You are getting this error because you have both netty shaded and pure grpc netty dependencies. Is it by purpose?

**Comment by mortenlocka** [comment]
Thanks! Found the missing exclusion. We have a lot of third party libs that pull in grpc-netty.

On 4.5.0 I end up here: https://github.com/LogNet/grpc-spring-boot-starter/blob/cc33050833f7f0decf461b8bc79e53e9bd489725/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/security/AuthenticationSchemeService.java#L26

Does not happen on 4.4.6. Having to set grpc.security.auth.enabled=false was new in 4.5.0?

**Comment by jvmlet** [comment]
By default, starter pulls `io.grpc:grpc-netty-shaded` as transitive dependency, if you are forced to use pure `grpc-netty`dependency:

 compile ('io.github.lognet:grpc-spring-boot-starter:4.5.0') {
  exclude group: 'io.grpc', module: 'grpc-netty-shaded'
 }

**Comment by jvmlet** [comment]
Which dependency you include for security?
