### ISSUE TITLE
Change github repo description.

### ISSUE THREAD

**Issue by otrosien** [LogNet/grpc-spring-boot-starter#21]
Repo description incorrectly states "Spring Boot starter module for Google RPC".
Should be "for the gRPC framework."

**Comment by jvmlet** [comment]
Hi
Are you looking at latest version ? It's `gRPC framework`, not `Google RPC`

**Comment by otrosien** [comment]
I'm not talking about the README file, but the description line within github. Screenshot here: http://picpaste.com/pics/Screenshot-X9dnJmxk.1472405887.png

**Comment by jvmlet** [comment]
Fixed, thanks.
