### ISSUE TITLE
How to monitor multiple ports upgrade v2

### ISSUE THREAD

**Issue by jojoti** [LogNet/grpc-spring-boot-starter#213]
issue: https://github.com/LogNet/grpc-spring-boot-starter/issues/174

Sorry, now I want to upgrade the version of grpc starter. The previous issue solved a part of the problem of external and internal calls of a server frontend process, but @GRpcService could not distinguish their respective entrances. In other words, the required internal cluster traffic and External traffic including grpc BindableService needs to be deployed separately. This is the case when building a grpc service in golang. We use two ports to distinguish between terminal call traffic and cluster call traffic. The user terminal, such as the traffic sent by js client using grpc, needs to be separated from the internal traffic of the cluster.

**Comment by jojoti** [comment]
The traffic between the terminal traffic and the service requires separate authentication.

**Comment by jojoti** [comment]
thx

**Comment by jvmlet** [comment]
Sorry, but I'm not following you. By `monitor` you mean `metric collection` or something else ?

**Comment by jojoti** [comment]
Such as:
Client : web browser
Service A: listen grpc 8001, 8002
Service B: listen grpc 9001, 9002

user access:

Client -> Service A Grpc port 8001
Client -> Service B Grpc port 9001

service invoke:

Service A -> Service B Grpc port 9002
Serivice B -> Serivce A Grpc port 8002

**Comment by jvmlet** [comment]
So you have 2 instances of grpc servers , first with service A and second with service B ?

**Comment by jojoti** [comment]
yeah, listen 4 ports. Take different permission checks.

**Comment by jvmlet** [comment]
So you have `address` tag in micrometer (`hos`t+`port`) and you can also add your [own tags](https://github.com/LogNet/grpc-spring-boot-starter#441-custom-tags-support). What is missing ?

**Comment by jojoti** [comment]
yeah
