### ISSUE TITLE
Can't download version 4.5.1 from maven central

### ISSUE THREAD

**Issue by ParadoxShmaradox** [LogNet/grpc-spring-boot-starter#217]
Hey,

Updating the version to 4.5.1:

        <dependency>
            <groupId>io.github.lognet</groupId>
            <artifactId>grpc-spring-boot-starter</artifactId>
            <version>4.5.1</version>
        </dependency>

Fails because the jar file couldn't be found.
Looking in: https://repo.maven.apache.org/maven2/io/github/lognet/grpc-spring-boot-starter/4.5.1/

It seems like the jar file has the suffix "-plain": grpc-spring-boot-starter-4.5.1-plain.jar    

Which didn't exist for previous releases.

**Comment by jvmlet** [comment]
You are right, thanks for reporting. 
Spring boot `2.5.0` adds `plain` qualifier  to jar task. Will be fixed. Meanwhile you can add `plain` qualifier to the dependency

**Comment by jvmlet** [comment]
```
<dependency>
        <groupId>io.github.lognet</groupId>
        <artifactId>grpc-spring-boot-starter</artifactId>
        <version>4.5.1</version>
<classifier>plain</classifier>
    </dependency>

```
