### ISSUE TITLE
Has the minimum jdk version changed?

### ISSUE THREAD

**Issue by heowc** [LogNet/grpc-spring-boot-starter#218]
I tried to use the recently released 4.5.2, but I was unable to use it facing the following:
```
Caused by:
             java.lang.NoSuchMethodError: java.util.Optional.or(Ljava/util/function/Supplier;)Ljava/util/Optional;
                 at org.lognet.springboot.grpc.autoconfigure.NettyServerBuilderSelector.selectImports(NettyServerBuilderSelector.java:46)
                 at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:581)
                 ... 113 more
```

`Optional.or(...)` is available since java 9. Is this the intended behavior?

See https://docs.oracle.com/javase/9/docs/api/java/util/Optional.html#or-java.util.function.Supplier-
See https://github.com/heowc/SpringBootSample/pull/449/checks?check_run_id=2759829808#step:8:424

**Comment by jvmlet** [comment]
`sourceCompatibility` and `targetCompatibility` are set to `11`

**Comment by jvmlet** [comment]
I [see ](https://github.com/heowc/SpringBootSample/blob/main/.github/workflows/test.yml)that you are using `java-version: 8.0.282+8`

**Comment by nodh** [comment]
> `sourceCompatibility` and `targetCompatibility` are set to `11`

But I see that it's 1.8!?
https://github.com/LogNet/grpc-spring-boot-starter/blob/6b20e31af54c2fe2e360509576331c7e7c093f0f/build.gradle#L45

**Comment by jvmlet** [comment]
You are right, I looked at wrong branch.
This is strange, `4.5.2` was succesfully compiled with `jdk 11`  and `sourceCompatibility` and `targetCompatibility` set to 1.8

**Comment by heowc** [comment]
If there is a sudden version change, I think it is necessary to document this. 🤔

**Comment by heowc** [comment]
By the way, many open sources support at least jdk 1.8, so I would like to keep it as it was before. 🤣

**Comment by jvmlet** [comment]
@heowc , you are  totally right, I'll definitely do (support `1.8`), but I wonder why the build didn't fail with `targetCompatibility =1.8` and sources with language features from `1.9` ...

**Comment by jvmlet** [comment]
```
tasks.compileJava {
    options.compilerArgs.addAll(["--release", "8"])
}
```
did the trick, without this java simply trusts you without  enforcing the language level

**Comment by heowc** [comment]
The open-source I use has the same option 👍

https://github.com/line/armeria/blob/master/build.gradle#L161...L163

**Comment by heowc** [comment]
Alternatively, we can use the following options:

See https://docs.gradle.org/current/userguide/toolchains.html
See https://github.com/spring-projects/spring-framework/blob/38b592444d463b09016b3fe3631bb2ab0a63270e/gradle/toolchains.gradle

**Comment by jvmlet** [comment]
thanks @heowc , I think I'll use `options.compilerArgs.addAll(["--release", "8"])` because tool chain slows down the build by installing `jdk1.8`

**Comment by jvmlet** [comment]
`4.5.3` was releases
