### ISSUE TITLE
Document  GRPC starter + Kafka Stream usage

### ISSUE THREAD

**Issue by jedvardsson** [LogNet/grpc-spring-boot-starter#219]
Hi, I am having problem starting a spring cloud app using this project when no Kafka is available, which is normal in development. The app will hang until KafkaAdminClient times out after 60 s before the app is fully started.

What happens is that the bean `grpcInternalConfigurator` which is defined as a `Consumer<ServerBuilder<?>>` seems to request a Kafka Topic. This is because spring cloud streaming treats beans of `Consumer`, `Supplier` and `Function` as part of their messing system. 

I am not sure if the intent of `GRpcAutoConfiguration` is to depend on this feature. From what I can tell it does not look so, however, I am a novice in this area so I could be wrong.

**Comment by jvmlet** [comment]
`GRpcAutoConfiguration` doesn't depend on Kafka. I'll check
 ```
This is because spring cloud streaming treats beans of Consumer, Supplier and Function as part of their messing system.
```
If you could provide the project that reproduces the behavior, it would be great.

**Comment by jedvardsson** [comment]
Great, I'll fix a minimal project to reproduce the issue shortly.

**Comment by jvmlet** [comment]
Thanks @jedvardsson, I'll have a look

**Comment by jvmlet** [comment]
@jedvardsson , according to [this](https://github.com/spring-cloud/spring-cloud-function/issues/418), we will need to explicitly set the consumer/producer function definitions, no way to mark the Consumer/Produce/Function   beans as not eligible for registration.
I'll commit the  demo with test for this use case soon

**Comment by jvmlet** [comment]
@jedvardsson , [this is essential ](https://github.com/LogNet/grpc-spring-boot-starter/blob/c4b89e443a02ba950115985274d38d8cdbc6ba13/grpc-spring-boot-starter-demo/src/test/resources/bootstrap-kafka-test.yml#L22)if you have more than 1 Consumer/Producer/Function bean.
Demo test is [here](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/kafka/GrpcKafkaTest.java)

**Comment by jvmlet** [comment]
@jedvardsson ,[FYI](https://github.com/LogNet/grpc-spring-boot-starter#spring-cloud-stream-support)
