### ISSUE TITLE
grpc-kotlin-stub version is not same grpc version

### ISSUE THREAD

**Issue by amondnet** [LogNet/grpc-spring-boot-starter#224]
Error:
```
Could not find io.grpc:grpc-kotlin-stub:1.38.0.
```

https://github.com/LogNet/grpc-spring-boot-starter/blob/26b4944d7b067e9be7fd984d76d5ef0577a13468/grpc-spring-boot-starter-gradle-plugin/src/main/resources/grpc-spring-boot.gradle#L14

https://github.com/grpc/grpc-kotlin is 1.1.0
https://github.com/grpc/grpc-java is 3.8.0

grpc-kotlin and grpc-java have the same group id ("io.grpc"), could not resolve `grpc-kotlin-stub`.

**Comment by jvmlet** [comment]
Thanks for reporting, will be fixed

**Comment by jvmlet** [comment]
@amondnet , btw, in kotlin project, do you still use `grpc java protoc` plugin  or there is  `grpc kotlin protoc` plugin ?

**Comment by amondnet** [comment]
@jvmlet I use both.  
https://github.com/grpc/grpc-kotlin/tree/master/compiler

```
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:SOME_VERSION"
    }
    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:SOME_VERSION"
        }
        id("grpckt") {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:SOME_VERSION:jdk7@jar"
        }
    }
    generateProtoTasks {
        ofSourceSet("main").forEach {
            it.plugins {
                id("grpc")
                id("grpckt")
            }
        }
    }
}

```

**Comment by jvmlet** [comment]
@amondnet , can you please try with `4.5.5-SNAPSHOT`

**Comment by jvmlet** [comment]
@amondnet , `4.5.5` was released
