### ISSUE TITLE
how to use io.github.lognet with gRPC and HTTP REST Api?

### ISSUE THREAD

**Issue by liuqixing** [LogNet/grpc-spring-boot-starter#228]
i found a way to write proto file like this:
service EchoService {
  rpc Echo(EchoMessage) returns (EchoMessage) {
    option (google.api.http) = {
      post: "/v1/echo"
      body: "*"
    };
  }
}

and i hope it works for me, but nope, it always returns error.
is anybody here know how to make it works?
thank you so much!

**Comment by jvmlet** [comment]
Please follow [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) documentation
