### ISSUE TITLE
SecurityInterceptor does not consult the GRpcErrorHandler for auth scheme selection errors

### ISSUE THREAD

**Issue by jGleitz** [LogNet/grpc-spring-boot-starter#229]
For example, `BearerTokenAuthSchemeSelector` throws a `OAuth2AuthenticationException` if a bearer token is malformed. Since the error handler is not consulted, we cannot remap this exception. As a consequence, our service returns the code `Unknown`, although it should be `Unauthorized`.

**Comment by jGleitz** [comment]
We can currently work around this issue by building an interceptor that has higher precedence than the `SecurityInterceptor`. Still it would be easier if the `GRpcErrorHandler` could handle it.

**Comment by jvmlet** [comment]
@jGleitz ,I've refactored the test [a bit](https://github.com/LogNet/grpc-spring-boot-starter/commit/71ab5a2ac0b4b99910cbcb2a11da2527b287721c)
