### ISSUE TITLE
gradle build exception

### ISSUE THREAD

**Issue by wzlee** [LogNet/grpc-spring-boot-starter#23]
`exception`
➜  grpc-spring-boot-starter git:(master) gradle build --info
Starting Build
Settings evaluated using settings file '/Users/leo/Documents/git/grpc-spring-boot-starter/settings.gradle'.
Projects loaded. Root project using build file '/Users/leo/Documents/git/grpc-spring-boot-starter/build.gradle'.
Included projects: [root project 'org.lognet', project ':grpc-spring-boot-starter', project ':grpc-spring-boot-starter-demo']
Evaluating root project 'org.lognet' using build file '/Users/leo/Documents/git/grpc-spring-boot-starter/build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/leo/Documents/git/grpc-spring-boot-starter/build.gradle' line: 45

* What went wrong:
A problem occurred evaluating root project 'org.lognet'.
> Could not find method compileOnly() for arguments [org.projectlombok:lombok:1.16.6] on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@61ff6a49.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 3.334 secs
Stopped 0 compiler daemon(s).

**Comment by jvmlet** [comment]
You should be using **gradlew** , not  **gradle** to build :
`gradlew build --info`
