### ISSUE TITLE
Propagate Authentication to SecurityContextHolder

### ISSUE THREAD

**Issue by jvmlet** [LogNet/grpc-spring-boot-starter#234]
See[ this discussion ](https://github.com/LogNet/grpc-spring-boot-starter/issues/157#issuecomment-880196062 )
@markbanierink, FYI

**Comment by jvmlet** [comment]
@markbanierink, would you please post a snippet here how you use `@PreAuthorize` annotation from `grpc` service

**Comment by markbanierink** [comment]
Sure!

Our gRPC service looks pretty much like this:
```java
@GRpcService
public class EntityServiceImpl extends EntityServiceGrpc.EntityServiceImplBase {
	
	@Autowired
	private DomainService domainService;

	@Override
	public void doFromRemote(EntityProtos.EntityRequest request, StreamObserver<EntityProtos.EntityResponse> responseObserver) {
		var entityA = request.getEntityA();

		var valB = domainService.doSomething(entityA);

		EntityProtos.Entity respVal = EntityProtos.Entity.newBuilder().setValue(valB).build();
		var responseBuilder = EntityProtos.EntityResponse.newBuilder();
        	responseBuilder.addSomeValue(respVal);

        	responseObserver.onNext(responseBuilder.build());
        	responseObserver.onCompleted();
	}

}
```
And the domain service:
```java
@Component
public class DomainService {

	@PreAuthorize("hasPermission(#entityA.id, permission)")
	public Object doSomething(EntityA entityA) {
		// do something after permission was checked
	}

}
```

**Comment by jvmlet** [comment]
Thanks @markbanierink. I've integrated your PR, had to refactor a bit because of merge conflicts. All tests are passing, I'll commit tomorrow. I'll also try to support `@PreAuthorize`on grpc service /method. Currently it's working only for downstream services. I'll need to have special  grpc method invoker to go through proxied grpc service in order to evaluate the annotation' s expression

**Comment by jvmlet** [comment]
@markbanierink , did you have to add `@EnableGlobalMethodSecurity(prePostEnabled = true)` somewhere in your app to enable the enforcement of `@PreAuthorize` ?

**Comment by markbanierink** [comment]
Yes, it has to be configured:

```java
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class SecurityConfiguration {
    // some beans
}
```

**Comment by jvmlet** [comment]
@mark, as I understand, you don't use `grpc security` feature, right ? Only pure spring boot security infrastructure, right ?

**Comment by markbanierink** [comment]
Euhm.. I'm not sure what you mean, but we do have a configuration for the grpc security too:
```java
@Configuration
public class CustomGrpcSecurityConfigurerAdapter extends GrpcSecurityConfigurerAdapter {

    @Override
    public void configure(GrpcSecurity builder) throws Exception {
        builder.authorizeRequests().anyMethod().authenticated();
    }
}
```
But yes, for the rest we only use spring security.

**Comment by jvmlet** [comment]
@markbanierink , I've committed the changes from your PR #233.
I'm talking about another issue I'm experiencing  with `@PreAuthorize` support, lets continue at #175
