### ISSUE TITLE
Custom service health check support

### ISSUE THREAD

**Issue by bigsky-033** [LogNet/grpc-spring-boot-starter#242]
I have a question about health check service. Looks like when I launch spring boot application server with LogNet/grpc-spring-boot-starter, health check service is added by `GRpcServerRunner.class`.

My question is, if I want to add my custom `HealthGrpc.HealthImplBase`, how can I do that properly? What I tried was registering my custom implementation of HealthGrpc.HealthImplBase as @GRpcService. In this way, it seems that my custom HealthGrpc.HealthImplBase, which I implemented, handles the request when a request is coming to 'grpc.health.v1.Health/Check'. But I'm not sure this is the right way to do that. 

So could you please let me know what is the right way to register custom health check service?

**Comment by jvmlet** [comment]
I'll provide configuration to support custom for health service registration. What you are doing  is fine, just need to disable the default one, I will make it optional.

**Comment by bigsky-033** [comment]
Thanks @jvmlet ! Looking forward to see that option.

**Comment by jvmlet** [comment]
@bigsky-033 , with `4.5.7-SNAPSHOT` you can register your `GRpcHealthStatusManager` bean with custom health check service, demo is [here](https://github.com/LogNet/grpc-spring-boot-starter/blob/47cc9f2f56ff32ee8f0be382ee8f55ace97676df/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/health/CustomGRpcHealthStatusManagerTest.java#L43)

**Comment by jvmlet** [comment]
You might also be interested in consul health check and registration modes support added in the same PR.
I don't think the default SINGLE-SERVER-GLOBAL-CHECK mode makes sense if you  are using consul with custom health check. I'll update readme soon, but you can see the code and control the consul registration mode with `grpc.consul.registrationMode` property

**Comment by bigsky-033** [comment]
Thanks @jvmlet for the information and I think just seeing code is enough for me. Thanks for your kindness.

**Comment by jvmlet** [comment]
@bigsky-033, I had to redesign the custom health check support a bit to make it  `@GRpcService` compatible  (support security, custom interceptors, metrics ect ). Please inherit you implementation from  `ManagedHealthStatusService` and register with  `@GRpcService` annotation, see updated [demo ](https://github.com/LogNet/grpc-spring-boot-starter/blob/03248ac5bcd0a6ffb73827caaae8dec00d8e403e/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/health/CustomManagedHealthStatusServiceTest.java#L33)

**Comment by jvmlet** [comment]
`4.5.7` released

**Comment by bigsky-033** [comment]
Thanks @jvmlet !
