### ISSUE TITLE
Support separate set of tags for grpc services in case both grpc and http services registration

### ISSUE THREAD

**Issue by OverDrone** [LogNet/grpc-spring-boot-starter#250]
Hello!
Starting from some version now grpc automatically registers itself on consul. I have TWO registrations now: `<service name>` and `grpc-<service name>` both with same set of tags. There is no way I can separate those two by tags or keep only `<service name>`. The only way is to filter by service name prefix `grpc-`, which is a very bad practice (what if I want to name my service `grpc-something`?). Currently I have to use awkward `spring.autoconfigure.exclude` (which doesn't concat automatically if specified in several profiles, see https://stackoverflow.com/questions/41170316/combine-list-from-multiple-spring-boot-yaml-files).
Here are few suggestions I have:
1. Add a separate setting for enabling grpc consul (and probably other servers) registration. See `OnConsulRegistrationEnabledCondition` which requires both `spring.cloud.service-registry.enabled` and `spring.cloud.consul.service-registry.enabled` flags. We can disable all auto registration or only consul auto registration this way. For grpc you might wanna check both `spring.cloud.service-registry.enabled` and `spring.cloud.grpc.discovery.service-registry.enabled`
2. Add grpc service registration tags which override `spring.cloud.consul.discovery.tags` when applied to grpc service registration like `spring.cloud.grpc.discovery.tags`
3. Extract `grpc-` hardcode into config to something like `spring.cloud.grpc.discovery.service-prefix`

**Comment by jvmlet** [comment]
@OverDrone , where did `proxy-` prefix come from ? May be you meant  `grpc-` prefix ?
Can you please confirm  you have `spring-boot-web` starter dependency in your app ?

**Comment by OverDrone** [comment]
> where did `proxy-` prefix come from
Yes, sorry, I meant "grpc-". Edited original post

**Comment by jvmlet** [comment]
> what if I want to name my service grpc-something

In this case grpc service registered name  for app named `grpc-something` will be `grpc-grpc-something`

**Comment by OverDrone** [comment]
[I use nginx consul template](https://learn.hashicorp.com/tutorials/consul/load-balancing-nginx) which reads info from consul and builds nginx config. Process rely on tags to determine whether to include this service in route, what url suffix to use etc. But generally that doesn't matter much. Generally I see no reason keeping 2 registrations on consul for the same app instance. Also this way consul would call health checks twice for the same instance. Ofcause I can't say that my usecase is valid for all users out there, I've seen your configuration where for each GRPC service you create separate registration on consul. But at least give an option to control this.

**Comment by jvmlet** [comment]
> Generally I see no reason keeping 2 registrations on consul for the same app instance. Also this way consul would call health checks twice for the same instance.

The  health check is performed on service instance, not on app instance. I can imagine the situation where single app instance provides several services instances  - some of them can become unhealthy and the rest services remain healthy. And  its up to you to decide how to check health (globally or per service). Moreover , if you serve  both `http` and `grpc`  services in the same app instance, the health check is still not the same , even if you health-check globally, but per protocol (`http` and `grpc`) .

But I do understand the need to distinguish services at least by tag and the requirements to provide different set of tags for `http` and `grpc` services separately. The fastest you can get is that I add `NOOP` registration strategy in the nearest snapshot.

Later, I'll also provide configuration for `ConsulDiscoveryProperties` source binding (defaults to `spring.cloud.consul.discovery` prefix)

**Comment by OverDrone** [comment]
Yes, that should do it for me, thx. I don't require hotfix solution. I can live with spring.autoconfigure.exclude for some time. Take your time to build quality product :)

**Comment by jvmlet** [comment]
@OverDrone , FYI, see #251 , `2.5.8-SNAPSHOT` should be published in few minutes
