### ISSUE TITLE
How could I use grpc-spring-boot-starter with spring-boot-starter-data-mongodb

### ISSUE THREAD

**Issue by duluosheng** [LogNet/grpc-spring-boot-starter#26]
I try to use grpc-spring-boot-starter with mongodb, and I choose spring-boot-starter-data-mongodb, but 
it can't autowire to MongoRepository.

@GRpcService
public class IndicateService extends IndicateServiceGrpc.IndicateServiceImplBase {

    @Autowired
    DailyBarRepository dailyBarSearchRepository;
    
    ....
}

**Comment by jvmlet** [comment]
What is the exception you are getting?

**Comment by duluosheng** [comment]
Sorry, I forget to add "@EnableMongoRepositories". It's OK now.
Thank you for your reply.
