### ISSUE TITLE
Is there a way to intercept RuntimeException ?

### ISSUE THREAD

**Issue by smallufo** [LogNet/grpc-spring-boot-starter#27]
In gRPC , how to add a global exception interceptor that intercepts any `RuntimeException` and propagate meaningful information to the client ?

for example , a divide method may throw `ArithmeticException` with `/ by zero message` . In the server side , I may write :

```
@Override
public void divide(DivideRequest request, StreamObserver<DivideResponse> responseObserver) {
  int dom = request.getDenominator();
  int num = request.getNumerator();

  double result = num / dom;
  responseObserver.onNext(DivideResponse.newBuilder().setValue(result).build());
  responseObserver.onCompleted();
}
```

If the client passes denominator = 0 , it will get :

`Exception in thread "main" io.grpc.StatusRuntimeException: UNKNOWN`
And the server outputs

```
Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2@62e95ade
java.lang.ArithmeticException: / by zero
```
The client doesn't know what's going on.

If I want to pass `/ by zero` message to client , I have to modify server to : 
```
try {
    double result = num / dom;
    responseObserver.onNext(DivideResponse.newBuilder().setValue(result).build());
    responseObserver.onCompleted();
  } catch (Exception e) {
    logger.error("onError : {}" , e.getMessage());
    responseObserver.onError(new StatusRuntimeException(Status.INTERNAL.withDescription(e.getMessage())));
  }
```
And if client sends denominator = 0 , it will get :

```
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: / by zero
```
Good , `/ by zero` is passed to client.

But the problem is , in a truly enterprise environment, there will be a lot of `RuntimeExceptions` , and if I want to pass these exception's messages to client , I will have to try catch each method , which is very cumbersome.

Is there any global interceptor that intercepts every method , catching `RuntimeException` and trigger onError and propagate the error message to client ? So that I don't have to deal with `RuntimeExceptions` in my server code .

I try to do like this :  
```
@GRpcGlobalInterceptor
public class MyInterceptor implements ServerInterceptor {

  private Logger logger = LoggerFactory.getLogger(getClass());

  @Override
  public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call,
                                                               Metadata headers,
                                                               ServerCallHandler<ReqT, RespT> next) {
    logger.info("intercept {}", call.getMethodDescriptor().getFullMethodName());
    try {
      return next.startCall(call, headers);
    } catch (Throwable e) {
      logger.error("Throwable : {}" , e.getMessage());
      Status status = Status.INTERNAL.withDescription(e.getMessage());
      // then ?
      return ???
    }
  }
}
```

But it seems it cannot catch the `Throwable` when I pass denominator = 0 . 

I am stuck here ...

Any hints ?

Thanks

**Comment by jvmlet** [comment]
I remember I saw the thread at grpc forum with discussion about how exception should be passed to client... let me find the link.

**Comment by jvmlet** [comment]
Hi
You can find the discussion here  : https://github.com/grpc/grpc-java/issues/681 
The error handling example  is here : https://github.com/dconnelly/grpc-error-example
Hope this helps
I'm going to close this issue as it references grpc specific issue  rather grps spring boot starter .
