### ISSUE TITLE
Add support for Spring Boot 2.6

### ISSUE THREAD

**Issue by galvo** [LogNet/grpc-spring-boot-starter#270]
Is it possible to add support for Spring Boot 2.6, from https://github.com/LogNet/grpc-spring-boot-starter/blob/master/ReleaseNotes.md it looks like the latest version supported is 2.5.6

Many thanks

**Comment by marcorotondi** [comment]
Any news?

**Comment by jvmlet** [comment]
Please try with `4.6.0-SNAPSHOT`

**Comment by jvmlet** [comment]
`4.6.0` released

**Comment by galvo** [comment]
Much appreciated
