### ISSUE TITLE
Upgrade grpc to 1.43.x

### ISSUE THREAD

**Issue by mskutlu** [LogNet/grpc-spring-boot-starter#271]
Hello, 
io.grpc has m1 mac support from 1.42.1 and from 1.43.0 it has native support but lognet works with 1.42.0 so i cant use them on m1 mac. Can you update io.grpc to 1.43 or at least 1.42.1?

**Comment by jvmlet** [comment]
Please try with `4.6.0-SNAPSHOT`

**Comment by paulius-p** [comment]
> Please try with `4.6.0-SNAPSHOT`

Would it be possible to release a stable version?

**Comment by jvmlet** [comment]
`4.6.0` released
