### ISSUE TITLE
Unable to Implement Message Validation

### ISSUE THREAD

**Issue by Steam1996** [LogNet/grpc-spring-boot-starter#272]
Hello,

l've followed [the document for message validation](https://github.com/LogNet/grpc-spring-boot-starter#6-implementing-message-validation), but it does not seem to be working.

I created `constraints-hello.xml` under `resources/META-INF`.

```
<constraint-mappings
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://xmlns.jcp.org/xml/ns/validation/mapping"
        xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/validation/mapping
            http://xmlns.jcp.org/xml/ns/validation/mapping/validation-mapping-2.0.xsd"
        version="2.0">

    <bean class="com.hello.grpcHelloWorld.proto_gen.hello.HelloServiceOuterClass$HelloRequest">
        <getter name="firstName">
            <constraint annotation="javax.validation.constraints.NotEmpty"/>
        </getter>
    </bean>
</constraint-mappings>
```

`HelloService.proto`:

```
syntax = "proto3";
option java_multiple_files = true;
package com.hello.grpcHelloWorld.proto_gen.hello;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service HelloService {
  rpc ExecuteHello(HelloRequest) returns (HelloResponse) {};
}

message HelloRequest {
  string firstName = 1;
  string lastName = 2;
  repeated string strings = 3;
  map<string, int32> map = 4;
}

message HelloResponse {
  string greeting = 1;
  google.protobuf.Timestamp createdDate = 2;
}
```

When I set  `{ "firstName": ""  }` or `{ "firstName": null }, it still passed; error for `NotEmpty` was not thrown. Am l missing something or how can I implement a message validation?

**Comment by jvmlet** [comment]
Have added spring boot validation as dependency?

**Comment by jvmlet** [comment]
You also should include your constraints xml into `META-INF/validation.xml`

**Comment by Steam1996** [comment]
> 

l've added the dependency, and yes, `validation.xml` was what l was missing. Thanks a lot! I also changed `    <bean class="com.hello.grpcHelloWorld.proto_gen.hello.HelloServiceOuterClass$HelloRequest">` to `    <bean class="com.hello.grpcHelloWorld.proto_gen.hello.HelloRequest">`.

Thank you.
