### ISSUE TITLE
Enable users to configure the error handling interceptor precedence

### ISSUE THREAD

**Issue by frenicth** [LogNet/grpc-spring-boot-starter#276]
I have a use case where I need the GRpcExceptionHandlerInterceptor to have a lower precedence. Is there a reason why this is not configurable in the same way as the auth, validation and metric interceptors?

https://github.com/LogNet/grpc-spring-boot-starter/blob/c85845eb0d5e1db061fa6b605c989d2691486b0b/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/recovery/GRpcExceptionHandlerInterceptor.java#L16

**Comment by jvmlet** [comment]
Good question. I couldn't think about the case where you would want to opt out from handling the exception. Can you please describe yours?
 I'll expose the property to define the order of the exception handling interceptor.

**Comment by frenicth** [comment]
I have an interceptor that manages trace information on logs. In the GRpcExceptionHandlerInterceptor I need to handle the error and log it where the trace information is needed. In the current implementation this information is lost because my interceptor is finished before the GRpcExceptionHandlerInterceptor. Does my reasoning make sense?

**Comment by jvmlet** [comment]
You can use grpc current  Context to pass the info you need down to the chain and get ahold of it in your error handler. 
While I think the error handling interceptor has to be the topmost and you should not move it, I'll expose the property just for completnes of API.

**Comment by jvmlet** [comment]
It might be that the context you set in interceptor 1 won't be available in interceptor the wraps it. In this case you can do try/catch, log the error with trace info and rethrow the exception. Or throw GRpcRuntimeExceptionWrapper with a hint (your trace info) and get ahold of it in handler and log it.

**Comment by frenicth** [comment]
Hm, we're actually overriding the onMessage method in the ServerInterceptor and everything that is logged inside  super.onMessage gets the "correct" trace information and format. So we're not really passing information around in that sense.

**Comment by jvmlet** [comment]
So its like MDC  attribute in slf4j?

**Comment by jvmlet** [comment]
BTW, the actual service method is not invoked /might not be invoked  in onMessage. Depends on rpc call type. For  request/reply it will be invoked in onHalfClose

**Comment by frenicth** [comment]
We're doing it like this
```
@Override
public void onMessage(ReqT message) {
  try (Scope s = setupCurrentTraceContext() {
    log.debug("First log with correct trace information");
    super.onMessage(message); // <- All logs with correct trace information
    log.debug("Last log with correct trace information");
  }
}
```

**Comment by jvmlet** [comment]
Is it for streaming call? I bet unary call won't have the trace context.

**Comment by frenicth** [comment]
I'm actually not feeling so confident in the solution, it's old inherited code but it looks something like this
```
@GRpcGlobalInterceptor
public class GrpcServerRequestInterceptor implements ServerInterceptor {

    @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> serverCall,
                                                                 Metadata metadata, ServerCallHandler<ReqT, RespT> serverCallHandler) {

        ServerCall.Listener<ReqT> listener = serverCallHandler.startCall(serverCall, metadata);
        return new ForwardingServerCallListener.SimpleForwardingServerCallListener<>(listener) {

            @Override
            public void onMessage(ReqT message) {
                try (Scope s = setupCurrentTraceContext()) {
                    log.debug("First log with correct trace information");
                    super.onMessage(message); // <- All logs with correct trace information
                    log.debug("Last log with correct trace information");
                }
            }

            @Override
            public void onHalfClose() {
                try (Scope s = setupCurrentTraceContext()) {
                    log.debug("First log with correct trace information");
                    super.onHalfClose(); // <- All logs with correct trace information
                    log.debug("Last log with correct trace information");
                }
            }
        };
    }
}
```
I've been reading up on interceptors and seen a lot of different solutions... I might have to fully understand how this actually works.

**Comment by jvmlet** [comment]
OK. So the service method is invoked either from onMessage (for streaming call) or onHalfClose  (for  unary call). They are both wrapped. Just add catch, log the error for the same scope and rethrow the exception.

**Comment by jvmlet** [comment]
`4.6.0` released
