### ISSUE TITLE
NPE thrown when trying to discover annotations on AOP Proxy objects

### ISSUE THREAD

**Issue by pluppens** [LogNet/grpc-spring-boot-starter#28]
In version 0.0.6, the org.lognet.springboot.grpc.GRpcServerRunner#run method tries to discover the `@GRpcService` annotation. However, this fails if the `bindableService` is wrapped as an AOP proxy.

A possible fix would be to check if the `bindableService` is a Proxy, and use its target class instead to find the `@GRpcService` annotation.

**Comment by jvmlet** [comment]
Hi, I've release version 0.0.7 with the fix, you are welcome to upgrade.

**Comment by pluppens** [comment]
@jvmlet Awesome, thanks. I'll give it a spin later today.

**Comment by jvmlet** [comment]
Would you please share your AOP configuraltion ?
I've managed to have proxied services, but the proxy is never called ... See AopServiceMonitor.java and DemoAppTestAop.java  in demo project.

**Comment by pluppens** [comment]
Hi @jvmlet, unfortunately, I didn't have time yet to verify things (will probably happen during the weekend). But just as a heads up - we're using Javanica annotations on our service methods, which caused the behaviour reported above.

**Comment by jvmlet** [comment]
Thanks for the update. I'll give Javanica a try.

**Comment by pluppens** [comment]
Other than that, I can confirm that things are working fine for us in 0.0.7. Thanks again!
