### ISSUE TITLE
`GrpcSecurityConfigurerAdapter` doesn't seem to be working

### ISSUE THREAD

**Issue by tobq** [LogNet/grpc-spring-boot-starter#281]
```java
@Configuration
public class GrpcSecurityConfiguration extends GrpcSecurityConfigurerAdapter {
    @Override
    public void configure(GrpcSecurity builder) throws Exception {
        var authenticationProvider = JwtAuthProviderFactory.forAuthorities(token -> ...);
        authenticationProvider.setJwtAuthenticationConverter(jwt -> ...);

        builder.authorizeRequests()
                .withSecuredAnnotation()
                .authenticationProvider(authenticationProvider)
        ;
    }
}
```
For this snippet, neither the `withSecuredAnnotation` or `authenticationProvider` configurations seem to have any effect on how `org.lognet.springboot.grpc.security.SecurityInterceptor` handles authentication

**Comment by jvmlet** [comment]
What do you mean by this? The secured methods are not really secured? Can you post the grpc services code snippet, specially the annotations.

**Comment by tobq** [comment]
@jvmlet The main issue is the authentication provider is completely ignored, showing that this configuration class is not working as expected. A side effect is the secured annotations not working either

**Comment by jvmlet** [comment]
Can you please post your  dependencies , annotated  grpc service classes and `spring.security.oauth2.resourceserver.jwt.issuer-uri ` config

**Comment by jvmlet** [comment]
Also, please enable `debug` log level for `org.lognet` :
````
<logger name="org.lognet" level="debug"/>
````

**Comment by tobq** [comment]
> 

I'm not using `spring.security.oauth2.resourceserver.jwt.issuer-uri`, I'm using a **_custom_** authentication provider, but the authentication provider provider above is never even called. The `SecurityInterceptor ` simply creates a `BearerTokenAuthentication` from my authentication instead of hooking into my custom auth provider.

**Comment by jvmlet** [comment]
If you are using **custom** provider, why are you registering JWT Auth provider ? 
Set breakpoint in  `org.springframework.security.access.intercept.AbstractSecurityInterceptor::beforeInvocation` to see what's happening...

**Comment by tobq** [comment]
@jvmlet because I have my own custom JWT auth logic. The implementation of the auth provider is irrelevant, the main problem is the auth providers not even being used, this entire `GrpcSecurityConfigurerAdapter ` seems to be ignored

**Comment by tobq** [comment]
@jvmlet because I have my own custom JWT auth logic. The implementation of the auth provider is irrelevant, the main problem is the auth providers not even being used, this entire `GrpcSecurityConfigurerAdapter` seems to be ignored

**Comment by jvmlet** [comment]
Can you set breakpoint and see what's happening?

**Comment by tobq** [comment]
sorry I fixed it, i was following an example online but it turns out there was some more stuff missing @jvmlet 
```java
@Configuration
@AllArgsConstructor
public class GrpcSecurityConfiguration extends GrpcSecurityConfigurerAdapter {
    @Override
    public void configure(GrpcSecurity builder) throws Exception {
        var authenticationProvider = ...;
        
        builder.authorizeRequests()
                .anyMethod().authenticated()
                .and()
//                .withSecuredAnnotation()
                .authenticationProvider(authenticationProvider)
        ;
    }
}
```
Not sure how to get that secured annotation working...

**Comment by jvmlet** [comment]
Have you annotated your services with `Secured` annotation?

**Comment by tobq** [comment]
> Have you annotated your services with `@Secured` annotation?
> 
> https://github.com/LogNet/grpc-spring-boot-starter/blob/2db331d15bc484be64b6c85456bf6fb1d5048a4f/grpc-spring-boot-starter-demo/src/main/java/org/lognet/springboot/grpc/demo/SecuredGreeterService.java#L20

I added the secured annotation to my method (but not the service); should this work?

**Comment by jvmlet** [comment]
Yes, work both on service and method level. 
So before the methods weren't annotated? You need to use `withSecuredAnnotation()` when you added the annotation
