### ISSUE TITLE
gRPC 1.44.0

### ISSUE THREAD

**Issue by Akaame** [LogNet/grpc-spring-boot-starter#282]
Thanks for version `4.6.0` which upgraded to gRPC `1.43.2`. A newer rollout of gRPC libraries has happened which include some patching, especially ` netty-codec-http2` from `4.1.63` to `4.1.72`. Should we make this jump for the next patch version (`4.6.1`)?

Cheers.

**Comment by sheinbergon** [comment]
@jvmlet Any chance for this version bump/release?

**Comment by jvmlet** [comment]
`4.7.0` will use grpc `1.45.0`. Snapshot build is already available.
