### ISSUE TITLE
Multiple gRPC servers in 1 Spring Boot application

### ISSUE THREAD

**Issue by hansut** [LogNet/grpc-spring-boot-starter#288]
Hello, 
I would like to ask if it is possible to have multiple gRPC servers exposed by 1 Spring Boot application. E.g. 1 would run on port 9090 using plaintext, second one would run on port 9091 using TLS.
Thank you in advance.

**Comment by jvmlet** [comment]
I think the best way to deal with such requirement is to employ proxy, like `traefik` or `envoy`. You run `grpc-server`  with plain-text and proxy with 2 exposed ports (one with and second without tls) and the same grpc backend.
You then do SSL-termination on the one with TLS.
