### ISSUE TITLE
Weird exception after migration to 4.6.0 and spring-boot 2.6.6

### ISSUE THREAD

**Issue by vicmosin** [LogNet/grpc-spring-boot-starter#292]
Requests in integration tests started to fail with
`io.grpc.StatusRuntimeException: INTERNAL: Connection closed after GOAWAY. HTTP/2 error code: COMPRESSION_ERROR, debug data: Use direct accessor methods for pseudo headers.`

Any ideas? Not sure if it's starter or grpc related

**Comment by vicmosin** [comment]
Seems like upgrading grpc to 1.45.1 solves the issue.

**Comment by jvmlet** [comment]
Thanks for reporting, I'll build next version with `1.45.1`
