### ISSUE TITLE
Security API enhancements

### ISSUE THREAD

**Issue by vicmosin** [LogNet/grpc-spring-boot-starter#296]
Hi there,
I wonder whether we could have something like

```
override fun configure(builder: GrpcSecurity) {
        builder.authorizeRequests()
            .services(SomeServiceGrpc.getServiceDescriptor()).hasAnyRole(user) // fallback
            .methods(SomeServiceGrpc.getMethod1()).hasAnyRole(admin, user)
            .methods(SomeServiceGrpc.getMethod2()).hasAnyRole(superAdmin, user)
}
```

Idea is to have a fallback restriction to service's methods if one forgot to define the method restriction in configuration. Right now such approach doesn't seem to work. For example, the snippet above will set all the methods of the `SomeServiceGrpc` to have at least `user` role even if it's not explicitly specified in the configuration

Thank you

**Comment by jvmlet** [comment]
I'm not sure I understand
>>the snippet above will set all the methods of the SomeServiceGrpc to have at least user role even if it's not explicitly specified in the configuration

is exactly the fallback you are asking, no?

**Comment by vicmosin** [comment]
@jvmlet 
well, the problem is that `.method(*)` definition doesn't seem to override the `.services(*)`, buy  technically yeah, fallback works

**Comment by jvmlet** [comment]
@vicmosin , I think this is what you are after :

````java
 builder.authorizeRequests()
            .services(SomeServiceGrpc.getServiceDescriptor()).hasAnyRole(admin)  
            .anyServiceExcluding(SomeServiceGrpc.getServiceDescriptor()).hasAnyRole(user)
````
Please try with latest `4.7.1-SNAPSHOT` once [build ](https://app.travis-ci.com/github/LogNet/grpc-spring-boot-starter/builds/251758553) completes.
You also have similar API for `methods`

**Comment by jvmlet** [comment]
`4.7.1` is out

**Comment by vicmosin** [comment]
@jvmlet thnx for quick solution but I think there is still something either wrong there or I do it wrong.. for example,

```
.methods(
   SomeServiceGrpc.getCreateXMethod(),
).hasAnyRole(admin)
.anyMethodExcluding(
   *SomeServiceGrpc.getServiceDescriptor().methods.toTypedArray()
).hasAnyRole(user)
```

now with such config if I call createX without providing auth details, the call goes through.. if I revert to 4.7.0 and define all the methods individually then it works as expected

**Comment by jvmlet** [comment]
Such config leaves all `SomeServiceGrpc` methods, except `createXMethod`, unprotected, right? BTW, such config still allows `user` role to call `createXMethod`.
Are you sure the unauthorized user can invoke `createXMethod`?

**Comment by jvmlet** [comment]
They are not `fallback`. Each time you invoke   `hasAnyRole()` method , the authority is  (authorities are)  added to the permission list of the `MethodDescriptor`.
At runtime, if the  `MethodDescriptor` has the user role in it's  authorities list   - it's allowed.
