### ISSUE TITLE
Configurable server

### ISSUE THREAD

**Issue by pierrebelzile** [LogNet/grpc-spring-boot-starter#30]
Hi,

Thanks for this project. It's a great example. I'm trying to use it and the server configuration is too limited (e.g., no TLS). From the variety of examples in Google, it seems that it is not likely that all solutions could be covered using a general properties file. Therefore I would suggest using a bean for the ServerBuilder. Idea is that application would provide with the end point configured. You could then add to it the discovered services and their interceptors. The current code would be changed to locate the bean from the ApplicationContext. If the bean can't be retrieved, then the code would instantiate one using the current port configuration capability. What do you think?

Cheers, Pierre

**Comment by jvmlet** [comment]
Hi Pierre
Indeed, the `custom configuration` was on the road-map ... 
I think I'll be able to add this feature in the nearest future.
Stay tuned

**Comment by jvmlet** [comment]
Hi
You can grab version 1.0.0 that support custom configuration.
Please refer to README for more details and share your experience
