### ISSUE TITLE
Prevent grpc service method to be called by multiple clients at the same time

### ISSUE THREAD

**Issue by TaridaGeorge** [LogNet/grpc-spring-boot-starter#309]
I have a @GRpcService annotated class which overrides my service rpc methods. Is there a configuration that I can made in order to prevent concurrent access on that method?

My code look something like this:

```
@GRpcService
public class MyClass extends MyServiceImplBase {

    @Override
    @Transactional
    public void myServiceMethod(request, responseObserver) {
        // run a select query that retrieves a row from db
        // set retrieved to true in database for the retrieved row
        // save updated row to database
    }
}
```

The problem is that If I have 2 grpc clients calling this method at the same time the method will return the same row.

**Comment by jvmlet** [comment]
You can use traditional Java  synchronization mechanisms to protect critical sections, including DB transactions, nothing grpc-special.
Also I recommend to read this section carefully https://github.com/LogNet/grpc-spring-boot-starter#grpc-response-observer-and-spring-transactional-caveats

**Comment by TaridaGeorge** [comment]
As you advised, I've moved my DB transaction logic into a service and annotated that method with @Transactional.
I've also tried to use syncronized keyword and a ReentrantLock but sometimes it still returns the same row from the database.

My code look something like this now:

```
@GRpcService
public class MyClass extends MyServiceImplBase {

    private final Lock methodLock = new ReentrantLock();

    @Override
    public void myServiceMethod(request, responseObserver) {
        methodLock.lock();
        // row = run a select query that retrieves a row from db
        responseObserver.onNext(row);
        responseObserver.onCompleted();
        // row.retrieved = True -> call service method annotated with @Transactional to set retrieved to true in database for the retrieved row
        methodLock.unlock();
    }
}
```

Why would this not work?

**Comment by jvmlet** [comment]
What is your retrieve row logic?

**Comment by TaridaGeorge** [comment]
It's just a repo call to findAllByRetrievedIsNull

**Comment by TaridaGeorge** [comment]
What is strange is that before using the lock mechanism If I was calling the GRpcService method concurrently 5 times, 5 out of 5 times I would get the same row returned. After I've added the lock mechanism and moved the update row method into it's own service I'm getting the same row 2 out of 5 times.

My code in order to test this looks something like this:

```
    @Scheduled(fixedDelay = 1000)
    public void runTest() throws InterruptedException {
        log.info("Running tests");
        ExecutorService service = Executors.newFixedThreadPool(5);
        IntStream.range(0, 5)
                .forEach(count ->
                        service.submit(grpcClient::callMyServiceMethod));
        service.awaitTermination(100, TimeUnit.MILLISECONDS);
    }
```
