### ISSUE TITLE
HealthCheck

### ISSUE THREAD

**Issue by pink-lucifer** [LogNet/grpc-spring-boot-starter#31]
Greetings, thanks for the great contribution firstly, just wondering if possible to integrate with HealthStatusManager as part of the starter, and probably as well as consul(consul-template)/ or haproxy be part of the service discovery, governance utilities?

found ideas as this one: http://www.juhonkoti.net/2015/11/26/using-haproxy-to-do-health-checks-to-grpc-services

@GRpcService(grpcServiceOuterClass = HealthCheckServiceGrpc.class, serviceName = "HealthCheckGRpcService")
public class HealthCheckGRpcService extends HealthCheckServiceGrpc.HealthCheckServiceImplBase{

    @Autowired
    private HealthStatusManager healthStatusManager;

    @Override
    public void status(Health.StatusRequest request, StreamObserver<Health.HealthCheckResult> responseObserver) {
        Health.HealthCheckResult.Builder builder = Health.HealthCheckResult.newBuilder();
        builder.setStatus("1");
        responseObserver.onNext(builder.build());
        responseObserver.onCompleted();
    }

    @PostConstruct
    public void healthInit(){
        healthStatusManager.setStatus(this.getClass().getName(), HealthCheckResponse.ServingStatus.SERVING);
    }

    @PreDestroy
    public void healthDestroy(){
        healthStatusManager.clearStatus(this.getClass().getName());
    }
}

**Comment by jvmlet** [comment]
Hi
Nothing stops you from integrating this starter with great spring boot eureka support - I will add the example later to wiki page.
According to health indicators -  I think we should follow this guideline http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#_writing_custom_healthindicators
to expose the grpc health, and it should be exposed via http, not http2, to be consumed by existing tools, like spring boot admin. I'm thinking about custom http health indicator endpoint that will internally try built-in grpc service and return Health accordingly... 
Contributions are welcome :-)

**Comment by pink-lucifer** [comment]
Hi, 
Thanks a lot for your feedback, load balancer might be another topic, and after a glance at eureka , that should work. https://github.com/grpc/grpc-java/issues/428 similar talks here.
As per health check, custom indicator, can you share more details, i think i may come up some dev for you review.

i hava a folk on this, and merged consul register/deregister, as well as grpc HealthStatusManager for service monitoring.
my thoughts was consul was a very good product, support http, dns, however would cause additional cost,  haproxy is lightweight, and with keeplived could work well as a load balacer, and its health check and built-in monitor is also good thing, so trying to work out with consul-template, which would help output the configs change to haproxy cfg， as per health check, which could borrow the idea from the post, use the magic buffer... this could help especially when we are restarting the services.

cheers.

**Comment by jvmlet** [comment]
Hi, from my side, the only requirement  is that integration with other services should be covered by [spring cloud](http://cloud.spring.io/spring-cloud-static/Brixton.SR7/) abstractions.
Also, I want this starter to be lightweight, meaning that it has as less dependencies on other services as possible, letting end user to choose the services to integrate with to implement enterprise patterns.

**Comment by jvmlet** [comment]
is supported in upcoming  `4.5.9` release
