### ISSUE TITLE
<dependencyManagement> section from the grpc-spring-boot-starter's pom cause Maven to go into an endless loop trying to resolve dependency conflict over grpc

### ISSUE THREAD

**Issue by zartc** [LogNet/grpc-spring-boot-starter#314]
When including both io.github.lognet:grpc-spring-boot-starter and io.grpc:grpc dependencies in a pom there is a non negligible risk that maven encounter a dependency conflict about the grpc libs, which it is unable to resolve and caus it to goes into an infinite loop without emmiting any disgnostic message - you must kill maven to escape the endless loop.

In an attempt to understand what was going on, I finally took a drastic action and **removed the `<dependencyManagement>` section from the io.github.lognet:grpc-spring-boot-starter's pom** in my `.m2\repository\io\github\lognet\grpc-spring-boot-starter\4.8.1`

Then on next run, Maven emmit the below message: 
```
Could not resolve version conflict among [com.#####:###-commons-grpc:jar:1.0.2 -> io.grpc:grpc-services:jar:1.43.2 -> io.grpc:grpc-core:jar:[1.43.2,1.43.2], com.#####.###:protos:jar:1.0.0 -> io.grpc:grpc-netty-shaded:jar:1.49.0 -> io.grpc:grpc-core:jar:[1.49.0,1.49.0]]
```
ok, now I can manage to fix the issue.

The grpc dependency conflict is clearly a problem of our own, but the fact that maven goes into a endless loop without emitting a diagnostic message is a problem originating from the io.github.lognet:grpc-spring-boot-starter pom.

It may be a bug in Maven, but the fact is that removing the `<dependencyManagement>` section from the io.github.lognet:grpc-spring-boot-starter's pom cure the problem.

Please, can you remove  the `<dependencyManagement>` section from the deployed pom (using, for exemple, the flatten plugin) so that maven will not goes into an endless loop in case of unresolvable grpc dependencies conflit ?

**Comment by jvmlet** [comment]
Have you ran `mvn dependency:tree -Dverbose`

**Comment by zartc** [comment]
`maven-enforcer-plugin` with the [Banned Dependencies rules](https://maven.apache.org/enforcer/enforcer-rules/bannedDependencies.html) is definitively something we should add in our parent pom to force the grpc version. It will certainly not solve the root of the problem but it might prevent it to occurs by making us aware of the conflict coming from one of our shared lib.
Thanks for the pointer.

**Comment by jvmlet** [comment]
The `dependencyManagement` section gets created by `dependency-management-plugin` gradle plugin  https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/main/src/main/java/io/spring/gradle/dependencymanagement/maven/PomDependencyManagementConfigurer.java, need to  understand how to skip this

**Comment by jvmlet** [comment]
Please try `4.8.2-SNAPSHOT` once [this  ](https://app.travis-ci.com/github/LogNet/grpc-spring-boot-starter/builds/256392949) build finishes

**Comment by zartc** [comment]
almost good: there is still a compile dependency to org.springframework.boot:spring-boot-starter without a version number. This is upsetting Maven which marks its desaprobation with a warning log on the console.

`[WARNING] The POM for io.github.lognet:grpc-spring-boot-starter:jar:4.8.2-20221006.150135-1 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for io.github.lognet:grpc-spring-boot-starter:4.8.2-SNAPSHOT
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter:jar is missing.`

If you can, let this dependencies have and open range version number like `[2.7.0,)` and mark it as `<scope>provided></scope>` to prevent it to participate in the transitive dependencies list (i.e. let the user choose what version of springboot it use).

**Comment by jvmlet** [comment]
[this one ](https://oss.sonatype.org/service/local/repositories/snapshots/content/io/github/lognet/grpc-spring-boot-starter/4.8.2-SNAPSHOT/grpc-spring-boot-starter-4.8.2-20221006.201052-2.pom )looks ok , please refresh your dependency and validate.

**Comment by zartc** [comment]
Well, it failed again. Your new pom 4.8.2-SNAPSHOT is ok, Maven no longer shows a warning but it returns to its endless loop behavior on resolving dependencies.

I ran several tests, each time editing the 4.8.2-SNAPSHOT pom in my .m2 directory.

The resulting observations are as follows:

1. When all the dependencies in the `<dependencies>` section of your pom have a valid version number, Maven enters an endless loop to resolve the dependencies.

2. When at least one dependency in the `<dependencies>` section of your pom does not have its version number, Maven shows a warning about this fact and finally fails the build showing the error message about the insoluble conflict on the grpc jar.

3. When at least one dependency in the `<dependencies>` section of your pom has an INVALID version number (spring-boot-starter:2.7.7 for example), then Maven exhibits behavior 1 (the endless loop).

4. When both case .2 and case .3 exist in your pom, then Maven exhibits behavior 2 (failing and printing message about conflict).

My conclusion about this is: 
- The problem has nothing to do with the `<dependencyManagement>` section of your pom. 
- Its withdrawal has just induced a positive side-effect that put Maven into the case .2.
- There is no obvious links between having a dependency without its version number in the pom and having an unsolvable dependency conflict in the transitive dependency list. The first problem just prevent Maven to enter an endless loop trying to solve an unsolvable conflict.

Also
- My apologies for having taken you on a wrong track with me, you can restore your original version.
- I'll have to investigate this problem further and contact the Maven team.

**Comment by jvmlet** [comment]
It's OK, whatever it takes to see green checkmarks of tests results 😁
I hardly believe it's maven issue, because scenario is straightforward.
Anyway I would upgrade maven to the latest version and recheck environment settings (proxy /etc )
