### ISSUE TITLE
How to known the server close at client when use Server-Side-Stream

### ISSUE THREAD

**Issue by yuezheng** [LogNet/grpc-spring-boot-starter#322]
In my case, the client only send the first Request and the accept the stream from Server. But when the server closed, the Client is not aware of any events.
How do I make the Client aware of the Server Close，so that it can do reconnect.

**Comment by jvmlet** [comment]
Please ask such kind of questions in official repo/stackoverflow.
This repository only integrates the grpc server with spring boot
