### ISSUE TITLE
4.9.0 Build Failing

### ISSUE THREAD

**Issue by galvo** [LogNet/grpc-spring-boot-starter#323]
For 4.7.0 and 4.8.0 the project builds fine but as soon as i upgrade to 4.9.0 i get

`
 Could not resolve dependencies for project com.example:demo:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at io.github.lognet:grpc-spring-boot-starter:jar:4.9.0 -> io.grpc:grpc-services:jar:1.50.0 -> io.grpc:grpc-core:jar:[1.50.0]
`

To reproduce you can just generate a Spring boot project using the initializr (aither SB 2.7.4 or 2.7.5) and add the following dependency

```
		<dependency>
			<groupId>io.github.lognet</groupId>
			<artifactId>grpc-spring-boot-starter</artifactId>
			<version>4.9.0</version>
			<exclusions>
				<exclusion>
					<groupId>io.grpc</groupId>
					<artifactId>grpc-netty-shaded</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

**Comment by galvo** [comment]
It looks like this was introduced in 4.8.1

**Comment by jvmlet** [comment]
Can you please create the repo that reproduces  this?

**Comment by galvo** [comment]
Apologies, it was a local maven issue, `mvn clean install -U` resolved it
