### ISSUE TITLE
Upgrade to grpc-java 1.1.1

### ISSUE THREAD

**Issue by cbornet** [LogNet/grpc-spring-boot-starter#33]
https://github.com/grpc/grpc-java/releases/tag/v1.1.1

**Comment by cbornet** [comment]
Fast 👍 
I note that the 1.0.2 artifact was only available on jcenter. Could the artifacts be made also available on maven central ?

**Comment by cbornet** [comment]
Hi, it still seems only in jcenter (nothing in https://repo.maven.apache.org/maven2/org/lognet)

**Comment by jvmlet** [comment]
Yeah, not  published yet to  maven central ...

**Comment by jvmlet** [comment]
Would  please open another issue about publishing to maven central?
