### ISSUE TITLE
Unable to parse scopes/roles from JWT token

### ISSUE THREAD

**Issue by CleverUnderDog** [LogNet/grpc-spring-boot-starter#332]
After trying for two full days I am still unable to get @Secured("ROLE_ADMIN") to work. The problem seems to be that no authorities are parsed from the JWT token. I have tried to include it as a array under the following locations: 

```json
{
  "scope": [
    "ADMIN"
  ],
  "resource_access": {
    "roles": [
      "ADMIN"
    ]
  },
  "roles": [
    "ADMIN"
  ],
}
```
For me it seems like a potential cause for this issue is that Spring is not calling the right parser.

**Comment by jvmlet** [comment]
Authorities are pulled from provider URL, configured with standard spring properties
Please see this test https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/auth/JwtAuthorityTest.java, corresponding profile and base class that generates the token.

**Comment by CleverUnderDog** [comment]
Thanks for the reference! I feel kinda embarrassed now. I have seen all this already but I forgot, that I had implemented the JwtDecoder some time ago to handle all claims as plain strings. In this case I needed to pass it as an array or list and everything works fine now.
