### ISSUE TITLE
Spring Security integration returns wrong status code when the caller does not have permissions to execute the operation

### ISSUE THREAD

**Issue by schonbachler** [LogNet/grpc-spring-boot-starter#335]
When a service method is secured and called by a user that has insufficient permissions a UNAUTHENTICATED response is returned instead of a PERMISSION_DENIED response.

How to reproduce the issue:
Annotate a service method with `@Secured({"ROLE_myrole"})`.
Call the Method from a client that is not member of this role but is correctly authenticated.
The server responds with a UNAUTHENTICATED response.

Expected behaviour:
A PERMISSION_DENIED should be returned.

From the grpc documentation:

UNAUTHENTICATED: 

> The request does not have valid authentication credentials for the operation.

PERMISSION_DENIED: 

> The caller does not have permission to execute the specified operation. PERMISSION_DENIED must not be used for rejections caused by exhausting some resource (use RESOURCE_EXHAUSTED instead for those errors). PERMISSION_DENIED must not be used if the caller cannot be identified (use UNAUTHENTICATED instead for those errors).

**Comment by jvmlet** [comment]
What is the version you are using?

**Comment by schonbachler** [comment]
Yes, i verified, that the credentials are correct.
I use the latest version: 5.0.0.
