### ISSUE TITLE
ClientInterceptor Unable to inject globally?

### ISSUE THREAD

**Issue by zlx2019** [LogNet/grpc-spring-boot-starter#336]
ClientInterceptor Unable to inject globally?

**Comment by jvmlet** [comment]
You might get better support  if you explain the issue you are experiencing in  more than 4 words.

**Comment by zlx2019** [comment]
```java
    @Bean
    @GRpcGlobalInterceptor
    public ServerInterceptor serverInterceptor(){
        return new DefaultGrpcServerInterceptor();
    }
```
Injecting the server-side interceptor in this way can take effect

But why doesn't that work?
```java
    @Bean
    @GRpcGlobalInterceptor
    public ClientInterceptor clientInterceptor(){
        return new DefaultGrpcClientInterceptor();
    }
```

**Comment by jvmlet** [comment]
This starter is only for server side. You can manually create intercepted client as described in the doc.
