### ISSUE TITLE
Publish artifacts to maven central

### ISSUE THREAD

**Issue by cbornet** [LogNet/grpc-spring-boot-starter#34]

**Comment by jsonshen** [comment]
@cbornet You can use https://bintray.com/lognet/maven/grpc-spring-boot-starter

**Comment by cbornet** [comment]
@jsonshen thanks but the default maven repo is http://repo.maven.apache.org/maven2/org/ so it would be great to be able to get it from there.

**Comment by spudtheimpaler** [comment]
I would also appreciate this being in maven central - being in a large corp, we can't add extra repositories to our standard maven builds...

**Comment by jvmlet** [comment]
I'll try to accomplish this in the nearest future..
@spudtheimpaler , if you are using Artifactory (or similar), virtual repository should do the trick.

**Comment by spudtheimpaler** [comment]
Thanks @jvmlet - will be appreciated :)
And there is nothing _technically_ preventing me from using an alternative repo, it is an architectural restriction.

**Comment by jvmlet** [comment]
Hi
I [tried ](https://issues.sonatype.org/browse/OSSRH-31098)to create sonatype account   for group id `org.lognet`, but `lognet.org` domain   has to be owned by LogNet. 
I can use `io.github.lognet` instead of `org.lognet`, but this will require changes in your dependencies configurations.
What is your vote ? Should I switch form `org.lognet` to  `io.github.lognet` ?

**Comment by cbornet** [comment]
👍 for io.github.lognet

**Comment by jorgheymans** [comment]
:+1:  for switching.

Will the java packages change as well ?

**Comment by jvmlet** [comment]
> Will the java packages change as well ?

No, only the group id

**Comment by lldata** [comment]
I ran into this issue as well. I hope you will consider this enhancement. Thanks

**Comment by uromahn** [comment]
Still no artifact in Maven Central? :(

**Comment by cbornet** [comment]
Would a PR to change the package help ?

**Comment by jvmlet** [comment]
I'm not going to change the package, only the grop id

**Comment by jlindholm** [comment]
Any eta getting this on Maven Central? thanks.

**Comment by jvmlet** [comment]
Currently I'm stuck with Travis Windows cli issue that wrongly generates the signature ...

**Comment by djotanov** [comment]
Could we help anyhow to make this happen? Its taking too long for a simple change.

**Comment by smartwjw** [comment]
Any updates?

**Comment by jvmlet** [comment]
Closing as fixed. Please see [readme](https://github.com/LogNet/grpc-spring-boot-starter#2-setup)
