### ISSUE TITLE
How to detect the client has disconnected when use server-side streaming?

### ISSUE THREAD

**Issue by mobileharry** [LogNet/grpc-spring-boot-starter#360]
By using bidirectional streaming, the returned StreamObserver will detect the disconnected event of a client and then trigger the  OnComplete() event. But the server-side streaming doesn't provide a way to return a StreamObserver. How to detect the client has disconnected when use server-side streaming?

**Comment by jvmlet** [comment]
I suggest you to ask such kind of question in official `grpc-java` repository
