### ISSUE TITLE
Please update gRPC

### ISSUE THREAD

**Issue by NoahAndrews** [LogNet/grpc-spring-boot-starter#37]
You're doing this for free of course, so I'm definitely not complaining, but it would be pretty fantastic if we could count on this repository to be updated more quickly.

**Comment by NoahAndrews** [comment]
Looking at the sample program, is it normal to manually specify grpc as a dependency in addition to this spring boot starter?

**Comment by jvmlet** [comment]
I'll update to the latest grpc the day after tomorrow,  and yes, you can override the grpc version by having both grpc and this starter as dependencies I'm your project.

**Comment by NoahAndrews** [comment]
Great, thanks!
