### ISSUE TITLE
spring cloud config problem

### ISSUE THREAD

**Issue by payam-aibees** [LogNet/grpc-spring-boot-starter#377]
When I added `spring-cloud-starter-config` to my project and set the property `spring.cloud.config.enabled` to `false` in development mode, the gRPC Server could not be started.

**Comment by jvmlet** [comment]
Any errors? No one is telepath here 😃

**Comment by payam-aibees** [comment]
No, there is no error at all. It just won't run anymore. the 'start' method in the 'GRpcServerRunner' class no longer executes

**Comment by jvmlet** [comment]
Add diagnostic flag (--debug) and see why the grpc  server runner is not instantiated.
