### ISSUE TITLE
Allow order Interceptors by using @Order annotation in the @Bean definition

### ISSUE THREAD

**Issue by debraj-manna** [LogNet/grpc-spring-boot-starter#379]
We have a spring boot application that uses ServerInterceptors The problem I found is that if the @Order annotation is added to the @bean definition it won't have any effect.

```
@Bean
@Order(Ordered.HIGHEST_PRECEDENCE)
@GRpcGlobalInterceptor
public io.grpc.ServerInterceptor globalServerMicrometerInterceptor(
      final ObservationRegistry observationRegistry) {
    // for metric collection and distributed tracing
    return new ObservationGrpcServerInterceptor(observationRegistry);
}
```

And then another one

```
@Bean
@GRpcGlobalInterceptor
public io.grpc.ServerInterceptor globalServerInterceptor(...) {
...
}

```

But the second one is not running later than the first one. Can someone let me know how can I enforce this?

```
<grpc.springboot.starter.version>5.1.2</grpc.springboot.starter.version>
<spring-boot.version>3.0.11</spring-boot.version>
```

**Comment by debraj-manna** [comment]
The same has been fixed in https://github.com/yidongnan/grpc-spring-boot-starter/issues/627

**Comment by jvmlet** [comment]
As a quick work around you can have the interceptor you return to implement `IOrdered`

**Comment by debraj-manna** [comment]
@jvmlet We are using spring-boot 3.0.11. Fix is made in 5.1.5. Do I have to upgrade spring-boot also to 3.1.1 (as per the [version matrix](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/ReleaseNotes.md)) or I can use 5.1.5 with my current spring-boot 3.0.11?

**Comment by jvmlet** [comment]
`3.0.11` should be fine, release build is on the way ....

**Comment by jvmlet** [comment]
`5.1.5` was released
