### ISSUE TITLE
Spring Security Keycloak integration

### ISSUE THREAD

**Issue by artysed** [LogNet/grpc-spring-boot-starter#380]
Hey! 
Are there any examples of integration with keycloak using spring 3 security? 
Thank you.

**Comment by jvmlet** [comment]
All  tests auth tests are here
https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/auth

**Comment by jvmlet** [comment]
https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/auth/JwtAuthBaseTest.java this base class configures keyckoak integration

**Comment by artysed** [comment]
@jvmlet is there a way to register jwtAuthConverter similar how it's done for rest api: 
```java
.oauth2ResourceServer(oauth2 -> oauth2
                .jwt(jwt -> jwt
                    .jwtAuthenticationConverter(myConverter())
                )
            );
```
Thank you.

**Comment by artysed** [comment]
already find out. Basically created my own auth provider:
```java
@Override
  public void configure(GrpcSecurity builder) throws Exception {
    JwtAuthenticationProvider customJwtAuthenticationProvider =
        new JwtAuthenticationProvider(jwtDecoder());
    customJwtAuthenticationProvider.setJwtAuthenticationConverter(jwtAuthConverter);

    builder.authorizeRequests()
        .methods(AuthServiceGrpc.getSignUpMethod()).hasAnyRole("test")
        .and()
        .authenticationProvider(
            customJwtAuthenticationProvider);
  }
```

**Comment by jvmlet** [comment]
Please close the issue if you got the answer
