### ISSUE TITLE
Updating spring-boot to 3.2.0 breaks with "An AuthenticationManager is required"

### ISSUE THREAD

**Issue by benallard** [LogNet/grpc-spring-boot-starter#389]
I'm using the `spring-boot-starter-oauth2-resource-server`, and I thought that should be enough to setup the security processing.

Spring-boot 3.2.0 has spring-security 6.2

EDIT:
The AbstractSecurityInterceptor is actually deprecated:
> Use org.springframework.security.web.access.intercept.AuthorizationFilter instead for filter security, org.springframework.security.messaging.access.intercept.AuthorizationChannelInterceptor for messaging security, or org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor and org.springframework.security.authorization.method.AuthorizationManagerAfterMethodInterceptor for method security.

**Comment by alicanhaman** [comment]
I am currently updating to Spring boot 3.2.0. And faced the exact same issue. Our standart rest api security ended up breaking grpc, we don't do grpc security. Did you find a way to fix this issue?

**Comment by alicanhaman** [comment]
Disabled grpc security in properties which did the trick.

```
grpc:
  security:
    auth:
      enabled: false
```

**Comment by jvmlet** [comment]
Right, @alicanhaman, this is the way till 3.2.0 is supported.

**Comment by mwong38** [comment]
So grpc security doesn't work with 3.2.0 at all? When will 3.2.0 be supported? Is there a workaround in the mean time?

**Comment by jvmlet** [comment]
Hi, yes, planned. 
 Basically, they removed the filter that drives authentication , I asked spring security team to resurrect this class, but no 😒
What needs to be  done is to copy-paste the base class of grpc security interceptor (the essential part of it)

**Comment by sheinbergon** [comment]
@jvmlet will you accept PRs?

**Comment by jvmlet** [comment]
@sheinbergon, sure
FYI  https://github.com/spring-projects/spring-security/issues/13444

**Comment by debraj-spotnana** [comment]
https://grpc-ecosystem.github.io/grpc-spring/ started supporting spring boot 3.2.0

**Comment by benallard** [comment]
I just bumped to 3.3 (security 6.3), and it seems to work, so I will close that ticket.
