### ISSUE TITLE
Project EOL?

### ISSUE THREAD

**Issue by strax1e** [LogNet/grpc-spring-boot-starter#397]
Is this project still alive or has it been implicitly replaced by https://github.com/grpc-ecosystem/grpc-spring?

**Comment by strax1e** [comment]
No updates and commits for 8 months

**Comment by jvmlet** [comment]
No, not EOT and not replaced. 
Because of the situation in Israel  ...

**Comment by strax1e** [comment]
I didn't expect you to bring politics into your open-source project. Good, so you lost some of your users and fell further behind your competitor grpc-spring. Goodbye.

**Comment by jvmlet** [comment]
I prefer to lose them rather than let them benefit from it.
