### ISSUE TITLE
@Preauthorized annotation not working 

### ISSUE THREAD

**Issue by wjohnst3** [LogNet/grpc-spring-boot-starter#398]
Your doc shows an example of using Spring's @Preauthorized on a GRPC endpoint. I'm using a Reactor reactive endpoint. I see in your source code the use of the Secured annoation, but nothing about how to set up the Preauthorized stuff. Basically, it's not working for me. Can you expand your documentation a bit?

**Comment by jvmlet** [comment]
Please post your security adapter config and the usage of  `@PreAuthorize` attrubute (docs are [here](https://github.com/LogNet/grpc-spring-boot-starter?tab=readme-ov-file#103-preauthorize-and-postauthorize-support)):

**Comment by wjohnst3** [comment]
Thank you for getting back with me. I have not confirmed there is a bug per se, so the issue is most probably in my setup. 

Context: I have a Spring MVC app that uses Spring-Security. There exists GraphQL services and GRPC services.  Spring GraphQL uses method-level authorisation as well, and works as expected. Method-level stuff is enabled with @EnableMethodSecurity.

Issue: Method-level security is evaluated by the Grpc starter if I use @Secured; however, I need @PreAuthorized. Authorisation is simply skipped. 

I was kind of expecting Grpc requests to somehow hit the DefaultMethodSecurityExpressionHandler, then the PreAuthorizeAuthorizationManager::check, but they don't. Is it that more setup is needed with a reactive authorisation manager? An additional grpc interceptor? How is this suppose to work?

SpringBoot: 3.2.5
GrpcSpringBootStarter: 5.1.5

Grpc configuration. The provider is a custom provider, which is a class that simply implements AuthenticationProvider.
```
@Bean
public GrpcSecurity grpcSecurityConfiguration(SecurityAuthenticationProvider provider) {
    return new GrpcSecurity(provider);
}

@RequiredArgsConstructor
public class GrpcSecurity extends GrpcSecurityConfigurerAdapter {
    private final SecurityAuthenticationProvider provider;

    @Override
    public void configure(org.lognet.springboot.grpc.security.GrpcSecurity builder) throws Exception {
        builder.authorizeRequests()
                .anyMethod().authenticated()
                .and()
                .authenticationSchemeSelector(authorization -> ofNullable(authorization)
                        .map(bearer -> bearer.toString().replaceFirst(BEARER_PREFIX, ""))
                        .map(PreAuthenticatedJwtToken::new))
                .authenticationProvider(provider);
    }
}
```

Grpc controller function:
```
@Override
@PreAuthorize("hasAnyRole('SUPER','ADMIN','SYSTEM_R')")
public Mono<ProgramTemplateOutput> getProgramTemplateById(Mono<ID> request) {
   ...
}
```

**Comment by wjohnst3** [comment]
I'm walking through using @Secured. I swapped Preauthorised above to be @Secured("ROLE_SUPER")

1. Incoming call hits SecurityInterceptor, which calls function beforeInvocation.

2. Spring decide is called down the stack with the following state:
```
org.springframework.security.access.vote.AffirmativeBased::decide
 - authentication: UsernamePasswordAuthenticationToken [Principal=1, Credentials=[PROTECTED], Authenticated=true, Details=null, Granted Authorities=[ROLE_ADMIN]]
- object: method invocation [public reactor.core.publisher.Mono is.sidekick.proto.service.program.ReactorProgramServiceGrpc$ProgramServiceImplBase.getProgramTemplateById(reactor.core.publisher.Mono)]
- configAttributes:
    -- AuthenticatedConfigAttribute: (no value)
    -- SecurityConfig: [ROLE_SUPER]
```

3. Then the access decisions are handled.

```
getDecisionVoters: 
    - RoleVoter::rolePrefix: ROLE_
    - RoleVoter::rolePrefix: SCOPE_
    - AuthenticatedAttributeVoter: (no value)
    - GrpcSecurity

for (AccessDecisionVoter voter : getDecisionVoters()) {
    int result = voter.vote(authentication, object, configAttributes);
    switch (result) {
        case AccessDecisionVoter.ACCESS_GRANTED:
            return;
        case AccessDecisionVoter.ACCESS_DENIED:
            deny++;
            break;
        default:
            break;
    }
}
```

4. Here is the voter stuff.

```
public class AuthenticatedAttributeVoter implements AccessDecisionVoter<Object> {
  @Override
  public boolean supports(ConfigAttribute attribute) {
    return AuthenticatedConfigAttribute.class.isInstance(attribute);
  }

  @Override
  public boolean supports(Class<?> clazz) {
    return true;
  }

  @Override
  public int vote(
      Authentication authentication, Object object, Collection<ConfigAttribute> attributes) {
    return (authentication.isAuthenticated() && attributes.stream().anyMatch(this::supports))
        ? ACCESS_GRANTED
        : ACCESS_ABSTAIN;
  }
}
```

So, vote is called with attributes containing AuthenticatedConfigAttribute from the Grpc starter. Basically, if authenticated then attributes.stream().anyMatch(this::supports) is always true. What am I missing?

**Comment by wjohnst3** [comment]
I´m saying I have @Secured("ROLE_SUPER") on the method and I call it with an authenticated Jwt token with granted authorities ["ROLE_ADMIN"] and it passes authorisation.

If I use @PreAuthorized, method level the authorisation check is skipped all together.
