### ISSUE TITLE
grpc services and @Transactional

### ISSUE THREAD

**Issue by jorgheymans** [LogNet/grpc-spring-boot-starter#41]
Hi,

It seems that spring's @Transactional has no effect when used in a @GrpcService class. This is probably expected but nevertheless surprising. Integrating with spring's tx interceptor mechanics could make a worthy addition to this starter. 

(and no i don't have a PR ready)

**Comment by jvmlet** [comment]
Have you tried to autowire the transactional bean into grpc service?

**Comment by jorgheymans** [comment]
If you mean wiring a transactional facade yes that's fine and that's how we
do it now. But the fact that the grpcservice is a @Component and it's
methods look like the boundary methods of a traditional facade makes people
want to put annotations on them. At least that's what happened in our team
several times :-)

Op wo 24 mei 2017 23:53 schreef Furer Alexander <notifications@github.com>:

**Comment by jvmlet** [comment]
As I understand, the service method is being  invoked by grpc framework directly  and spring has no idea about it, that's why  it can't create transaction around the invocation... I think custom grpc interceptor is the way to apply the @transactional logic....

**Comment by jvmlet** [comment]
Another thought : I  was taught  to always have clear separation of responsibility layers : transport, business and data access. Having @transactional being applied to transport method  smells :-), at least for me. So,  IMHO, you should continue to have facade to integrate with DB. What is your opinion?

**Comment by jorgheymans** [comment]
yes the grpc interceptor would suffice for the basic case, and custom per-method transactional semantics are more easily expressed using the separate transactional facade. 

About the layer responsibility, It's the accepted way in java to pretend a clean architecture :-) . I tend to agree but for the simple case layering just bogs things down.

**Comment by pagrus7** [comment]
As a Spring framework user I confirm the natural expectation of @Transactional (and other Spring goodness) working for grpc services, just like it works for with e.g. spring MVC controllers and apache CXF services.

**Comment by jvmlet** [comment]
@pagrus7 , contributions are welcome.

**Comment by jorgheymans** [comment]
@pagrus7 how do you see this working with streaming rpc's ? The tx interceptor will only work well for the standard "simple RPC" case, once the client starts streaming you can no longer assume the same model applies. In some cases you might want to start a transaction server side per streaming call, whereas others would want the whole stream to be in the same transaction. You would probably need to implement a custom annotation or attribute on @GrpcService to express all these semantics. Don't think this a small feat :-)

**Comment by pagrus7** [comment]
@jorgheymans I agree that in streaming context the declarative transactions on GRPC service are unlikely to be useful. Can't think of a valid use case. Unary RPC calls though can get the most benefit from transactions, and there are tons of use cases for them.

In short, I see @Transactional working exactly like it would elsewhere: transaction opens before the method execution and commits right after. It is up to developer to decide on the meaningful use with respect to the RPC pattern they choose.

With all that said, based on a few experiments I suspect that transaction management (and other proxy-based goodness) _does work already_, assuming the right configuration is in place. Stay tuned as I'm writing the next comment.

**Comment by pagrus7** [comment]
[Here](https://github.com/pagrus7/grpc-spring-boot-starter/commit/089b0c08a3a52ae0e6f88ae1091d13fd61ed2098) is my example which combines @Transactional and @GRpcService. It configures spring for proxying target class rather than using dynamic proxies. `spring.aop.proxy-target-class=true` does the trick; `@EnableTransactionManagement(proxyTargetClass=true)` would also work. Then, when GRPC binds a service and passes `this` as a service impl, interceptors are still preserved.

Looks like [this proxy mode will be default in Spring Boot 2.x](https://github.com/spring-projects/spring-boot/issues/8786).

I encourage others to try switching from jdk proxies to cglib and see if it solves the problem for them.

**Comment by jorgheymans** [comment]
@pagrus7 interesting thanks, so it seems that at most this 'feature' would need a small section in the documentation explaining things - great :)

**Comment by jvmlet** [comment]
It's interesting to see that interceptors are invoked **before** the actual proxied service call, run the 
`DemoAppTestAop` test :

```
2017-10-10 13:28:25.870  INFO 8236 --- [    Test worker] o.lognet.springboot.grpc.DemoAppTestAop  : Started DemoAppTestAop in 3.083 seconds (JVM running for 4.273)
Greeter/SayHello
2017-10-10 13:28:26.224  INFO 8236 --- [ault-executor-0] o.l.springboot.grpc.demo.LogInterceptor  : Greeter/SayHello
2017-10-10 13:28:26.235  INFO 8236 --- [ault-executor-0] o.l.s.grpc.demo.AopServiceMonitor        : Hi from AOP. - before
2017-10-10 13:28:26.254  INFO 8236 --- [ault-executor-0] o.l.springboot.grpc.demo.GreeterService  : Returning Hello John
2017-10-10 13:28:26.255  INFO 8236 --- [ault-executor-0] o.l.s.grpc.demo.AopServiceMonitor        : Hi from AOP. - after
```

**Comment by pagrus7** [comment]
@jvmlet while I'm very new to GRPC, it looks like the interceptors are intended for _augmenting_ a chain of listeners and handlers, rather than _executing_ the cross-cutting logic in-place.

E.g. the following implementation of a logging interceptor
```java
    @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, Metadata headers,
                                                                 ServerCallHandler<ReqT, RespT> next) {

        ForwardingServerCall.SimpleForwardingServerCall loggingCall = new ForwardingServerCall.SimpleForwardingServerCall(call) {
            @Override
            public void sendMessage(Object message) {
                log.info("{} - responding with message - {} ", call.getMethodDescriptor().getFullMethodName(), message);
                super.sendMessage(message);
            }
        };

        ServerCall.Listener<ReqT> loggingListener = next.startCall(loggingCall, headers);
        SimpleForwardingServerCallListener loggingListenerWrapper = new SimpleForwardingServerCallListener(loggingListener) {
            @Override
            public void onMessage(Object message) {
                log.info("{} - received message - {} ", call.getMethodDescriptor().getFullMethodName(), message);
                super.onMessage(message);
            }

            @Override
            public void onComplete() {
                log.info("{} - call completed", call.getMethodDescriptor().getFullMethodName());
                super.onComplete();
            }
        };

        return loggingListenerWrapper;
    }
```

... produces the output which makes sense to me
```
2017-10-10 17:57:43.778  INFO 7924 --- [ault-executor-0] o.l.springboot.grpc.demo.LogInterceptor  : Greeter/SayHello - received message - name: "John"
 
2017-10-10 17:57:43.833  INFO 7924 --- [ault-executor-0] o.l.s.grpc.demo.AopServiceMonitor        : Hi from AOP. - before
2017-10-10 17:57:43.839  INFO 7924 --- [ault-executor-0] o.l.springboot.grpc.demo.LogInterceptor  : Greeter/SayHello - responding with message - message: "Hello John"
 
2017-10-10 17:57:43.843  INFO 7924 --- [ault-executor-0] o.l.springboot.grpc.demo.GreeterService  : Returning Hello John
2017-10-10 17:57:43.843  INFO 7924 --- [ault-executor-0] o.l.s.grpc.demo.AopServiceMonitor        : Hi from AOP. - after
2017-10-10 17:57:43.844  INFO 7924 --- [ault-executor-1] o.l.springboot.grpc.demo.LogInterceptor  : Greeter/SayHello - call completed
```

**Comment by jvmlet** [comment]
I would expect the `LogInterceptor` inerceptor to be executed **between** AopServiceMonitor's `@Before` and `@After` pointcuts, not vise versa...

**Comment by pagrus7** [comment]
Added a one-liner PR for README.adoc which mentions class proxying.

**Comment by jvmlet** [comment]
Still, if your interceptor requires  transaction, it will not be available... Only the service method itself will be transactional...

**Comment by pagrus7** [comment]
@jvmlet I think this is "business as usual". If an interceptor needs a transaction, it can start one.
To me, if grpc interceptors started joining business transactions without invitation (since only service implementation is annotated), it would come as a surprise.

**Comment by jvmlet** [comment]
@jorgheymans, what do you think? Should I close this issue?

**Comment by jorgheymans** [comment]
Yes can be closed, thanks !

Op di 10 okt. 2017 19:19 schreef Furer Alexander <notifications@github.com>:
