### ISSUE TITLE
No Support for Maven builds

### ISSUE THREAD

**Issue by uromahn** [LogNet/grpc-spring-boot-starter#49]
While I understand and appreciate your personal preference for Gradle, there are plenty of developers out that that use Maven for various good reasons.

Each and every Spring-related project should also have a Maven pom.xml included in it.

**Comment by jvmlet** [comment]
What would the ant lovers do then?

**Comment by uromahn** [comment]
The same what I did - complain that it is not supported.

But seriously, Ant is not that widely used anymore, especially in the 
enterprise world. I believe, Maven is still the most used build tool in 
the Java/JVM world by a large margin and hence I would consider Maven 
support a must.

Heck, I would even do it myself but unfortunately, my day job does not 
give me enough time and I also have a life and a family. :)

Cheers

------ Original Message ------

**Comment by jvmlet** [comment]
Closing the issue  due to the reason explained in l last paragraph of previous comment
