### ISSUE TITLE
Allow random port selection

### ISSUE THREAD

**Issue by dadadom** [LogNet/grpc-spring-boot-starter#51]
In order to test several gRPC components with each other, I have several Spring Boot projects with this starter. I need to ensure that I always set the grpc.port property to something unused whenever I create a new project.

Would it be possible to allow random port selection when specifying grpc.port = 0, like it is e.g. done for server.port to allow random ports for the embedded Tomcat/Jetty server?

I can only imagine that the service discovery example is then a bit more tricky.

**Comment by jvmlet** [comment]
Hi
This sounds like a reasonable request
You will be able to use `${local.grpc.port}`  to bind the generated value to eureka configuration when this request is implemented.

**Comment by jvmlet** [comment]
Well, it looks like you will **not**  be able to resolve the value from configuration file... Spring does not support it either ( [one](https://github.com/spring-projects/spring-boot/issues/5077) , [two](https://github.com/spring-projects/spring-boot/issues/7802) ). You will have to process the resolved value by yourself in java code ... Sorry.

**Comment by dadadom** [comment]
I fully understand why it's not possible to reference grpc.port within the configuration file, but I nevertheless think that it is a useful feature/config option.
We do the ServiceDiscovery programatically, anyway, and can remember the assigned port in the code, so the issue is not a problem for us.

**Comment by jvmlet** [comment]
> I fully understand why it's not possible to reference grpc.port within the configuration file, but I nevertheless think that it is a useful feature/config option.

Me either, I'll add this feature
