### ISSUE TITLE
not found variable log?

### ISSUE THREAD

**Issue by conanchen** [LogNet/grpc-spring-boot-starter#52]
just download the source code and import into intellij idea 2017.2, get the compiler complain: 
Error:(49, 9) java: 找不到符号
  符号:   变量 log
  位置: 类 org.lognet.springboot.grpc.GRpcServerRunner

line 49:   log.info("Starting gRPC Server ...");

**Comment by jvmlet** [comment]
How are you compiling : from Intellij Idea or Gradle ?
The project uses `Lombok` , so if you desperetly want to compile from IntelliJ, please enable  the annotation processor
![image](https://user-images.githubusercontent.com/6664858/29655372-90d418f2-88b9-11e7-8f39-2a80ecbf1add.png)
You can also install the Lombok plugin for IntelliJ
