### ISSUE TITLE
What is the difference to yidongnan's grpc-spring-boot-starter ?

### ISSUE THREAD

**Issue by MartinX3** [LogNet/grpc-spring-boot-starter#54]
What is the difference to https://github.com/yidongnan/grpc-spring-boot-starter ?

**Comment by jvmlet** [comment]
I think you should pose this question to yidongnan. His repo is basically the rework of saturnism's starter (see issue #1) with his additions he found useful to implement. 
I can only say that this one was developed by me from the scratch without being inspired by anyone else.
