### ISSUE TITLE
Testing non-blocking bidirectional transfer

### ISSUE THREAD

**Issue by filiphr** [LogNet/grpc-spring-boot-starter#55]
First of all, great job on the starter it is really light-weight and easy to use.

In your examples you have unary services only. I am using bidirectional services. Reading the gRPC documentation and recommendation they recommend using an `InProcessServerBuilder` for testing. However, I could not find a way to do this with the current setup. What do you propose I should do for something like this?

**Comment by jvmlet** [comment]
Thanks @filiphr 
There is PR #39, I just didn't have time so far to review and merger it.
Hope I'll do that .

**Comment by filiphr** [comment]
@jvmlet That is partial to what I want to do. I want to use `InProcessServerBuilder` only during tests and not during production. With the PR I can only mark services as `InProcess`

**Comment by jvmlet** [comment]
Totaly agree, that's why this PR is  still PR.

**Comment by filiphr** [comment]
That's great @jvmlet thanks a lot for integrating it.
