### ISSUE TITLE
build polishing

### ISSUE THREAD

**Issue by otrosien** [LogNet/grpc-spring-boot-starter#6]
Hi,

I'd like to contribute to this project. Based on my first glance I would have a few build improvements that come to my mind. Please give some feedback on how you like to see contributions (e.g. create / discuss issues first, only one issue per PR... etc)

- add gradle wrapper
- use "compileOnly" configuration from gradle 2.13
- upgrade dependencies (spring-boot, grpc, spring-cloud, lombok)
- missing .gitignore
- do you really want to check-in the generated code (grpc-spring-boot-starter-demo/src/protoGen/)

**Comment by otrosien** [comment]
current status https://github.com/otrosien/grpc-spring-boot-starter/tree/gradle-build

**Comment by jvmlet** [comment]
Hi, nice to see community environment. 
I'd prefer single issue per PR. 
As Read. me states, the generated classes were intentionally committed for demo purposes. 
Your PRs are welcome.

**Comment by otrosien** [comment]
Ok, thanks. I'll open separate issues for the items stated above.
