### ISSUE TITLE
SpringMvc integration

### ISSUE THREAD

**Issue by cforce** [LogNet/grpc-spring-boot-starter#62]
For existing Code Base and smooth integration it would be if advance when server side code first contract API can still be specified with/rebase on spring MVC anotations. Why not create proto files for clientd based on spring MVC enpoints an allow grpc server listen and converts spring MVC endpoints on server side without additional coding effort based on existing spring MVC projects.
Most advanced the grpc server runs besides existing SpringMvc servlet.

**Comment by jvmlet** [comment]
Does [this](https://github.com/grpc-ecosystem/grpc-gateway) answer yor question ? If not, please provide the sample with expected behaviour ...

**Comment by cforce** [comment]
Tx, that is very helpful but I still need to maintain a proto spec in paralell and sync with my SpringMvc  MVC rescontroller code first contract

**Comment by jvmlet** [comment]
Are you looking for a feature that generates `proto` service  from your existing mvc controller ?

**Comment by jvmlet** [comment]
You can maintain only the proto spec and use the `grpc-gateway` to support `http` clients

**Comment by IamRichie** [comment]
hah,i want to know,how to use it  ??i can"t understand your says...a  ha

**Comment by IamRichie** [comment]
i want to learn more in there😝😝😝,teach me please...

**Comment by cforce** [comment]
@jvmlet  Are you looking for a feature that generates proto service from your existing mvc controller ?

I knew that generating proto specs from MVC anotations is not supported so far / by grpc gateway. It was an idea for a missing link for a smooth integration or optional endpoint based on a a binaty protocol. Another approach would be to to setup grpc endpoints dynamically based on known SpringMvc annotation's  without intermediate proto spec..

**Comment by jvmlet** [comment]
I'm confused ;-) , **YOU** opened the issue to support grpc for existing mvc endoints...

**Comment by cforce** [comment]
yes, i did start discussion for a possible feature in this project. For projects heading towards hardware utilization and performance improvements  in (high load) microservice architectures (there are reason beyond that too of course) around overhead for json (de)marhsalling and thefore it is balid approach to offer an lower burden to migrate  towards an grpc based communication for existing sprint boot (mvc) applications, isn't it?

**Comment by jvmlet** [comment]
OK, I got your idea... So you want some kind of `@RestController bean post-processor` to dynamically  create and register service definitions, including the payload message format( `proto-buf` ) generation. Sorry, but this out of scope of this project.
