### ISSUE TITLE
2.1.2 can't be download from jcenter?

### ISSUE THREAD

**Issue by bearxyz** [LogNet/grpc-spring-boot-starter#66]
I use gradle to manage the jar files, but can't download the 2.1.2. And I check the jcenter repository, there is no 2.1.2 in it...

**Comment by jvmlet** [comment]
Hi
Thanks for pointing  out, please use  `compile('org.lognet:grpc-spring-boot-starter:2.1.3')`
I've updated the read.me as well.
Please confirm by closing the issue
Thanks again.

**Comment by bearxyz** [comment]
ok, problem solved, thanks!
