### ISSUE TITLE
Support gRPC 1.8.0

### ISSUE THREAD

**Issue by smartwjw** [LogNet/grpc-spring-boot-starter#67]

**Comment by jvmlet** [comment]
1.8.0 was released **10** hours ago and it's not even in maven central yet  ;-)

**Comment by jorgheymans** [comment]
would it be feasible to have embedding applications define or override the version of grpc used in this starter through a property they define ? would save you from catching up on all versions

**Comment by jvmlet** [comment]
@jorgheymans , you can override the version in your maven/gradle configuration, just include the compile dependency  of `grpc`  and you are done:
````
compile('org.lognet:grpc-spring-boot-starter:2.1.3')
compile "io.grpc:grpc-netty:${grpcVersion}"
compile "io.grpc:grpc-services:${grpcVersion}"
````

**Comment by jorgheymans** [comment]
Trusting maven to handle a transitive dependency override yeah that will go well, this is very flaky :)

**Comment by jvmlet** [comment]
I'm `gradle` fun, dependency resolution strategy works pretty well for me.
