### ISSUE TITLE
better shutdown ?

### ISSUE THREAD

**Issue by jorgheymans** [LogNet/grpc-spring-boot-starter#70]
I came across this on the grpc groups https://groups.google.com/d/msg/grpc-io/P5BFGoGxkbw/ozwwY9bDCQAJ and was wondering if GrpcServerRunner is doing enough by just calling shutdown

 ```
    @Override
    public void destroy() throws Exception {
        log.info("Shutting down gRPC server ...");
        server.getServices().forEach(def->healthStatusManager.clearStatus(def.getServiceDescriptor().getName()));
        Optional.ofNullable(server).ifPresent(Server::shutdown);
        log.info("gRPC server stopped.");
    }
```

From the post:

> server.shutdown(); // This simply prevents new RPCs
server.awaitTermination(5, SECONDS); // This is the grace time
server.shutdownNow(); // This kills all RPCs
// This needs some time to queue cancellation notifications.
// Note that terminated does not imply the application is done processing.
// It only means the server won't issue any more work to the application.
if (!server.awaitTermination(1, SECONDS)) {
  log.log(WARNING, "For some reason the server didn't shutdown promptly");
}
// After the server is terminated, all work has at least been queued onto the server's executor.
// You can shutdown and wait on that executor if you want. You can then also clean up services.
cleanUpServices();

**Comment by jvmlet** [comment]
I think yes, we are doing enough, because `GRpcServerRunner.this.server.awaitTermination();` is awoken   by ` Optional.ofNullable(server).ifPresent(Server::shutdown);`

**Comment by jvmlet** [comment]
BTW, they have the same in sample [here ](https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/advanced/HelloJsonServer.java)
