### ISSUE TITLE
Support gRPC 1.10 and Spring Boot 2.0

### ISSUE THREAD

**Issue by smartwjw** [LogNet/grpc-spring-boot-starter#75]
https://github.com/grpc/grpc-java/releases

**Comment by clun** [comment]
Hello, here is a sample up-to-date but without the grpc-starter for the moment
https://github.com/KillrVideo/killrvideo-java, tell us when ready, will update this code

**Comment by jvmlet** [comment]
I've upgrade the `grpc`  to  `1.10.0` (released under `2.2.0`).
If your  `2.0.0` spring boot app fails to start with this starter, please file the bug.
