### ISSUE TITLE
Update protobuf-gradle-plugin to get rid of Gradle warning

### ISSUE THREAD

**Issue by mangan77** [LogNet/grpc-spring-boot-starter#77]
The currently used protobuf-gradle-plugin uses a feature in Gradle that is deprecated in Gradle 5.0. I suggest an upgrade of the plugin to 0.8.5 to get rid of the warning. 

More info about the bug and fix: https://github.com/google/protobuf-gradle-plugin/pull/172

**Comment by jvmlet** [comment]
fixed
