### ISSUE TITLE
Two gRPC ports on start ?

### ISSUE THREAD

**Issue by chsi13** [LogNet/grpc-spring-boot-starter#86]
When start my spring boot project with gRPC starter , got 2 logs "info" "gRPC Server started, listening on address: 0.0.0.0 , port: 9090" and "gRPC Server started, listening on port: 6565".

Why 2 gRPC servers are started ? I see in yml config grpc.server.port and grpc.port .. what's the difference ?

**Comment by jvmlet** [comment]
Can you please share your `build.gradle` and `application.yml` ?

**Comment by chsi13** [comment]
Nothing specific to  grpc config in my yml file. 
And in my pom.xml 
```
spring:
  application:
    name: ehboxhc-authorization-service
  activemq:
    broker-url: tcp://localhost:61616
```
```
 <dependency>
            <groupId>org.lognet</groupId>
            <artifactId>grpc-spring-boot-starter</artifactId>
            <version>2.3.2</version>
        </dependency>
 <plugin>
            <groupId>org.xolstice.maven.plugins</groupId>
            <artifactId>protobuf-maven-plugin</artifactId>
            <version>0.5.1</version>
            <configuration>
                <protocArtifact>com.google.protobuf:protoc:3.5.1-1:exe:${os.detected.classifier}</protocArtifact>
                <pluginId>grpc-java</pluginId>
                <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.12.0:exe:${os.detected.classifier}</pluginArtifact>
            </configuration>
            <executions>
                <execution>
                    <goals>
                        <goal>compile</goal>
                        <goal>compile-custom</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
```

**Comment by jvmlet** [comment]
can you ping the repo url to have a look ?

**Comment by jvmlet** [comment]
or is it internal ?

**Comment by jvmlet** [comment]
Looks like you have this one   as well  in your classpath : https://github.com/yidongnan/grpc-spring-boot-starter , it's using 9090 by default

**Comment by chsi13** [comment]
![image](https://user-images.githubusercontent.com/6585992/41701515-0a011f4e-752d-11e8-91ee-2a15fc1e5f52.png)

![image](https://user-images.githubusercontent.com/6585992/41701537-1b4f55fe-752d-11e8-8431-f5d54093cfa3.png)

Like one start by the grpc  lib itself and the other by spring boot. 

When I call on 6565 I got response.

When I call on 9090 I got this --> Exception in thread "main" io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: be.fgov.grpc.AuthService/verify
****

**Comment by jvmlet** [comment]
What are the 2 classes names that print "grpc started at port " log info message?

**Comment by jvmlet** [comment]
Closing as lacking feedback
