### ISSUE TITLE
Upgrade protobuf-gradle-plugin

### ISSUE THREAD

**Issue by otrosien** [LogNet/grpc-spring-boot-starter#9]
Motivation:
- com.google.protobuf plugin is incompatible with latest gradle
- latest com.google.protobuf requires gradle 2.12+

Change:
- upgrade protobuf plugin to 0.7.7
- add gradle 2.13 as gradle wrapper

Result:
- we are aligned with latest plugin and gradle releases

**Comment by jvmlet** [comment]
Closed via #11 , thanks @otrosien
