### ISSUE TITLE
GRPC multiple connections

### ISSUE THREAD

**Issue by dzonekl** [LogNet/grpc-spring-boot-starter#90]
Hi, Thanks for your work. 

We would like to have the following clarified. We seem to observe that a connection gets overwritten when a second client would connect to a GRPC service (With same host/port), can you plz confirm this  implementation accepts multiple connections? 

We are noobs, regarding http/2 and how this will be dealt with in 'standard' sprint boot, perhaps spring boot or underlying tomcat needs to be configured with http/2 capabilities?  [1] I doubt any additional config is needed, as a single connection works nicely already. 

Additionally, we have a use case, that chunks of a service are implemented in separate classes, so we would a situation like this: 

`@GRpcService
public class AdyenNotificationService extends AdyenServiceGrpc.AdyenServiceImplBase
`

and

`@GRpcService
public class AdyenSessionService extends AdyenServiceGrpc.AdyenServiceImplBase
`

We get a io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method com.blox.vault.generated.AdyenService/GetStatus is unimplemented  on this call, which is in the 2nd implementation. Is this use case supported? 

[1] https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html#howto-configure-http2

Spring boot version: 2.0.4.RELEASE

gradle dependencies: 

grpcVersion = '1.13.1'
protobufVersion = '3.6.0'

 protobuf               : [
                    "com.google.protobuf:protobuf-java:$protobufVersion"
            ],
            gprc                   : [
                    "io.grpc:grpc-netty:$grpcVersion",
                    "io.grpc:grpc-protobuf:$grpcVersion",
                    "io.grpc:grpc-stub:$grpcVersion",
                    "io.netty:netty-tcnative-boringssl-static:$boringSslVersion"
            ],

regards, Christophe

**Comment by jvmlet** [comment]
Christophe, what do you mean by connecting gets overridden?
The class that inherits the stub has to implement all the methods, you can have one common basic class that implements basic method although and all others will derive from it.
Grpc comes with Netty by default

**Comment by dzonekl** [comment]
Hi, Thanks for clarifying on the stub implementation. On 'overridden' question, is so let's say we have two clients connecting to one server. What we observe is that the 2nd client, will break the connection from the first connection. I just want to check if this is our setup somehow. I would assume that the netty implementation supports multiple incoming http/2 connections, like regular http requests. Is this correct?  (I still need to do my homework on http/2).

**Comment by jvmlet** [comment]
Why do you think second client breaks the first client's connection? What is the exception? Can you post   the server method implementation that reproduces the behavior?

**Comment by dzonekl** [comment]
Hi, We have not investigated the problem yet, I just wanted to have a clarification on what is supported first. In the meantime, we are studying http/2 and grpc and server implementations like Netty. I think the answer is yes, it should support multiple connections, so we will investigate our issue. 
Thank You.
