### ISSUE TITLE
Unable to set GRPC_MAX_CONNECTION_AGE on grpc server

### ISSUE THREAD

**Issue by bob9** [LogNet/grpc-spring-boot-starter#91]
I would  like to be able to set the GRPC_MAX_CONNECTION_AGE as stated in load balancing kubernetes tutorial below.

https://github.com/jtattermusch/grpc-loadbalancing-kubernetes-examples
```
**Example 1: Round Robin Loadbalancing with gRPC's built-in loadbalancing policy**
Scale up again and watch the client pick up newly added backends. (_note that you need to set GRPC_MAX_CONNECTION_AGE on greeter-server to force periodical DNS re-resolution so that new backends can be picked up_).
```

I have not been able to find where to set this setting in grpc-spring-boot-starter.

**Comment by jvmlet** [comment]
Hi
You can add your custom gRPC Server Configuration as described [here](https://github.com/LogNet/grpc-spring-boot-starter#custom-grpc-server-configuration) , cast the passed builder to `NettyServerBuilder` and use it's API to customize everything

**Comment by bob9** [comment]
Thanks @jvmlet, appreciate the help. Here is the code if someone else has a similar issue. Casting was the secret.

`@Component
public class BillGrpcConfig extends GRpcServerBuilderConfigurer {


    @Value("${sniip.grpc.max_connection_age_seconds}")
    private int grpcMaxConnectionAgeSeconds;


    @Value("${sniip.grpc.max_connection_age_grace}")
    private int grpcMaxConnectionAgeGraceSeconds;

    @Override
    public void configure(ServerBuilder<?> serverBuilder) {
        super.configure(serverBuilder);
        ((NettyServerBuilder)serverBuilder).maxConnectionAge(grpcMaxConnectionAgeSeconds, TimeUnit.SECONDS);
        ((NettyServerBuilder)serverBuilder).maxConnectionAgeGrace(grpcMaxConnectionAgeGraceSeconds, TimeUnit.SECONDS);
    }
}
`
