### ISSUE TITLE
@LocalRunningGrpcPort fails without explicitly configured grpc.port

### ISSUE THREAD

**Issue by robfletcher** [LogNet/grpc-spring-boot-starter#93]
The README says configuring `grpc.port` is optional and it will default to `6565` but without configuring it my application fails at startup with ```IllegalArgumentException: Could not resolve placeholder 'grpc.port' in value "grpc.port !=0 ? ${grpc.port}:${local.grpc.port}"```

**Comment by robfletcher** [comment]
In fact, even with `grpc.port` specified it fails unless `local.grpc.port` is also set.

**Comment by robfletcher** [comment]
You can easily reproduce this by changing `GrpcServerTestBase` in the `grpc-spring-boot-starter-demo` subproject so that it looks like this:

```
    @LocalRunningGrpcPort
    protected int port;
    protected int getPort(){
        return  port;
    }
```

**Comment by jvmlet** [comment]
Thanks ,please upgrade to `2.4.1`

**Comment by nucle** [comment]
Hi,

thanks for the great work.

A few minutes ago i updated to the new version and i recognized that my ports are not the same as in the property files. I think the problem is that i use "the org.springframework.cloud:spring-cloud-starter-config". Mybe we need a check if cloud config is enabled.

greets

**Comment by jvmlet** [comment]
@nucle, are you setting `grpc.port` somewhere in yml or properties file?

**Comment by nucle** [comment]
Yes i'm setting grpc port in the yml files like this:
```
grpc:
  port: ${GRPC_PORT}

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
```

**Comment by jvmlet** [comment]
${GRPC_PORT} is taken from Config server? What is the port grpc uses when started with this configuration?

**Comment by nucle** [comment]
I am starting my service over docker. I can start multiple services on different ports.

docker run -p 1010:8888 -p 6566:6566 --network=my_network -e GRPC_PORT=6566 ...

${GRPC_PORT} is an environment variable.

**Comment by jvmlet** [comment]
Then why do you have
````
grpc:
 port: ${GRPC_PORT}
````

again in yml?
 Please try to remove this and retry. Setting `GRPC_PORT` environment variable should be enough.

**Comment by jvmlet** [comment]
@nucle , I've added the [test](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/EnvVarGrpcPortTest.java) to simulate your case, it's passed OK. 
If you still experiencing the problem, feel free to open the issue.

**Comment by nucle** [comment]
Sorry for the late response. It works! THX
