### ISSUE TITLE
Keycloak interceptors support ?

### ISSUE THREAD

**Issue by chsi13** [LogNet/grpc-spring-boot-starter#95]
For Rest communications we can use the keycloak starter to recover a Keycloak principal and add role-based authorization on server-side.

Is there something similar for grpc communications ?

I imagine that it will be implement as gRPC interceptors  ?

Thx

**Comment by jvmlet** [comment]
Please read [this](https://eng.revinate.com/2017/11/07/grpc-spring-security.html)
