### ISSUE TITLE
replacing tomcat with netty

### ISSUE THREAD

**Issue by chabmed** [LogNet/grpc-spring-boot-starter#96]
Hi, sorry this is not an issue it's more a question that i want to ask you. Actually i'm moving from rest to grpc. I still have to run tomcat for the admin port and some metrics related, but since including grpc so i'll have netty. However, i know that i can't replace tomcat with netty. (https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html) so i'll end up having both netty and tomcat. I just want to remove dependencies as much as possible here. Do you have any thoughts about that?
Thanks

**Comment by jvmlet** [comment]
Can you change your rest endpoints to be reactive or is it a massive change ? You will be able to include only Netty then...

**Comment by jvmlet** [comment]
> did you have the opportunity to try it?

No, but I don't see any reason this won't work.
