### ISSUE TITLE
kubernetes healthcheck

### ISSUE THREAD

**Issue by chabmed** [LogNet/grpc-spring-boot-starter#98]
Hi, 
I'm using the starter and i'm seeing that it actually exposes the grpc.health.v1.Health.Check. So in this case should we implement in our own a general server status. Because  for now i can check only when i specify the name of the service in healthcheck, but when i use an empty service name it returns an error of unknown service, 
"The server should use an empty string as the key for server's overall health status, so that a client not interested in a specific service can query the server's status with an empty request." https://github.com/grpc/grpc/blob/v1.15.0/doc/health-checking.md,
i'm actually deploying in kubernetes and i'm trying to use this grpc-health-probe
https://github.com/grpc-ecosystem/grpc-health-probe

Does it mean that i have to implement my own implementation, i'm not able to find the right answer for that. 

Thanks

**Comment by chabmed** [comment]
Hi, thanks for the hit, but that' not really what i'm looking for. I'm not sure but i think we are missing something here, or maybe we should implement it. Because it says "https://github.com/grpc/grpc/blob/master/doc/health-checking.md"
"The server should register all the services manually and set the individual status, including an empty service name and its status." 
The starter is already registering all the service manually with the status, but i think we are missing the empty service, to return the general health of the server,

**Comment by chabmed** [comment]
according to the code directly it's suppose to check all the grpc service, but it's still experimental, I also try to look into there code i didn't find any specific implementation of that so i'm wondering if the server had to implement or not. 
`@io.grpc.ExperimentalApi("https://github.com/grpc/grpc-java/issues/4696")
public final class HealthStatusManager {
  /**
   * The special "service name" that represent all services on a GRPC server.  It is an empty
   * string.
   */`

**Comment by chabmed** [comment]
Hi thanks, for the answer. I asked the question here:
https://groups.google.com/forum/#!msg/grpc-io/mfEc57yGLr0/mSjyz8p7BgAJ

> To use health-checking service, the application should create a HealthStatusManager and register getHealthService() to the server. The application can then set the serving status on the HealthStatusManager whenever desired. Because the serving status is always associated with a service, designated by a string, we define the empty string as the special service name to indicate the "whole server". This is a convention meant to communicate the health status of a whole server between the client and the server. The SERVICE_NAME_ALL_SERVICES constant is for the application server to use to set it, and for the application client to query it through RPC.

**Comment by balchua** [comment]
I've implemented this in our micro service.  We also added into our base image grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe binary.  And then we use the kubernetes exec in livenessProbe and readinessProbe.  

But yes you need to implement the Check method.

**Comment by jvmlet** [comment]
[FYI](https://github.com/LogNet/grpc-spring-boot-starter#9-health-check),  Supported via custom  [ManagedHealthStatusService](https://github.com/grpc/grpc-java/blob/bab1fe38dc/services/src/main/java/io/grpc/protobuf/services/HealthServiceImpl.java). 
The demo test that runs `slyncio/grpc-health-probe` docker is [here](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/health/CustomManagedHealthStatusServiceTest.java) ( uses grpc reflection to check each service separately)

**Comment by jvmlet** [comment]
https://github.com/grpc-ecosystem/grpc-health-probe/issues/92
